#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIB_Command_MoveTo

#include "Basic.hpp"


namespace SDK::Params
{

// Function AIB_Command_MoveTo.AIB_Command_MoveTo_C.ExecuteUbergraph_AIB_Command_MoveTo
// 0x0008 (0x0008 - 0x0000)
struct AIB_Command_MoveTo_C_ExecuteUbergraph_AIB_Command_MoveTo final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RunBehavior_ReturnValue;                  // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AIB_Command_MoveTo_C_ExecuteUbergraph_AIB_Command_MoveTo) == 0x000004, "Wrong alignment on AIB_Command_MoveTo_C_ExecuteUbergraph_AIB_Command_MoveTo");
static_assert(sizeof(AIB_Command_MoveTo_C_ExecuteUbergraph_AIB_Command_MoveTo) == 0x000008, "Wrong size on AIB_Command_MoveTo_C_ExecuteUbergraph_AIB_Command_MoveTo");
static_assert(offsetof(AIB_Command_MoveTo_C_ExecuteUbergraph_AIB_Command_MoveTo, EntryPoint) == 0x000000, "Member 'AIB_Command_MoveTo_C_ExecuteUbergraph_AIB_Command_MoveTo::EntryPoint' has a wrong offset!");
static_assert(offsetof(AIB_Command_MoveTo_C_ExecuteUbergraph_AIB_Command_MoveTo, CallFunc_RunBehavior_ReturnValue) == 0x000004, "Member 'AIB_Command_MoveTo_C_ExecuteUbergraph_AIB_Command_MoveTo::CallFunc_RunBehavior_ReturnValue' has a wrong offset!");

// Function AIB_Command_MoveTo.AIB_Command_MoveTo_C.GetScore
// 0x0004 (0x0004 - 0x0000)
struct AIB_Command_MoveTo_C_GetScore final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AIB_Command_MoveTo_C_GetScore) == 0x000004, "Wrong alignment on AIB_Command_MoveTo_C_GetScore");
static_assert(sizeof(AIB_Command_MoveTo_C_GetScore) == 0x000004, "Wrong size on AIB_Command_MoveTo_C_GetScore");
static_assert(offsetof(AIB_Command_MoveTo_C_GetScore, ReturnValue) == 0x000000, "Member 'AIB_Command_MoveTo_C_GetScore::ReturnValue' has a wrong offset!");

// Function AIB_Command_MoveTo.AIB_Command_MoveTo_C.PreCondition
// 0x0018 (0x0018 - 0x0000)
struct AIB_Command_MoveTo_C_PreCondition final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_FriendlyAIController_C*             K2Node_DynamicCast_AsBP_Friendly_AIController;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AIB_Command_MoveTo_C_PreCondition) == 0x000008, "Wrong alignment on AIB_Command_MoveTo_C_PreCondition");
static_assert(sizeof(AIB_Command_MoveTo_C_PreCondition) == 0x000018, "Wrong size on AIB_Command_MoveTo_C_PreCondition");
static_assert(offsetof(AIB_Command_MoveTo_C_PreCondition, ReturnValue) == 0x000000, "Member 'AIB_Command_MoveTo_C_PreCondition::ReturnValue' has a wrong offset!");
static_assert(offsetof(AIB_Command_MoveTo_C_PreCondition, K2Node_DynamicCast_AsBP_Friendly_AIController) == 0x000008, "Member 'AIB_Command_MoveTo_C_PreCondition::K2Node_DynamicCast_AsBP_Friendly_AIController' has a wrong offset!");
static_assert(offsetof(AIB_Command_MoveTo_C_PreCondition, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'AIB_Command_MoveTo_C_PreCondition::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AIB_Command_MoveTo_C_PreCondition, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000011, "Member 'AIB_Command_MoveTo_C_PreCondition::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");

}

