#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_762x39mm_FMJ_PROJ

#include "Basic.hpp"

#include "BP_BulletProjectile_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_762x39mm_FMJ_PROJ.BP_762x39mm_FMJ_PROJ_C
// 0x0000 (0x0338 - 0x0338)
class ABP_762x39mm_FMJ_PROJ_C final : public ABP_BulletProjectile_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_762x39mm_FMJ_PROJ_C">();
	}
	static class ABP_762x39mm_FMJ_PROJ_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_762x39mm_FMJ_PROJ_C>();
	}
};
static_assert(alignof(ABP_762x39mm_FMJ_PROJ_C) == 0x000008, "Wrong alignment on ABP_762x39mm_FMJ_PROJ_C");
static_assert(sizeof(ABP_762x39mm_FMJ_PROJ_C) == 0x000338, "Wrong size on ABP_762x39mm_FMJ_PROJ_C");

}

