#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DBAL_PL

#include "Basic.hpp"

#include "BP_DBAL_PL_classes.hpp"
#include "BP_DBAL_PL_parameters.hpp"


namespace SDK
{

// Function BP_DBAL_PL.BP_DBAL_PL_C.ExecuteUbergraph_BP_DBAL_PL
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DBAL_PL_C::ExecuteUbergraph_BP_DBAL_PL(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "ExecuteUbergraph_BP_DBAL_PL");

	Params::BP_DBAL_PL_C_ExecuteUbergraph_BP_DBAL_PL Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.CreateMIDsEvent
// (Event, Protected, BlueprintEvent)

void ABP_DBAL_PL_C::CreateMIDsEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "CreateMIDsEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.BndEvt__BP_DBAL_PL_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bLightActive                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bLightVisibility                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_DBAL_PL_C::BndEvt__BP_DBAL_PL_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature(bool bLightActive, bool bLightVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "BndEvt__BP_DBAL_PL_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature");

	Params::BP_DBAL_PL_C_BndEvt__BP_DBAL_PL_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature Parms{};

	Parms.bLightActive = bLightActive;
	Parms.bLightVisibility = bLightVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.BndEvt__BP_DBAL_PL_FlashLightComp_K2Node_ComponentBoundEvent_0_OnLightUpdate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bLightActive                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bLightVisibility                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_DBAL_PL_C::BndEvt__BP_DBAL_PL_FlashLightComp_K2Node_ComponentBoundEvent_0_OnLightUpdate__DelegateSignature(bool bLightActive, bool bLightVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "BndEvt__BP_DBAL_PL_FlashLightComp_K2Node_ComponentBoundEvent_0_OnLightUpdate__DelegateSignature");

	Params::BP_DBAL_PL_C_BndEvt__BP_DBAL_PL_FlashLightComp_K2Node_ComponentBoundEvent_0_OnLightUpdate__DelegateSignature Parms{};

	Parms.bLightActive = bLightActive;
	Parms.bLightVisibility = bLightVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.OnBeingUnequipped
// (Event, Public, BlueprintEvent)

void ABP_DBAL_PL_C::OnBeingUnequipped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "OnBeingUnequipped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.AddIR
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      UsageMenu                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DBAL_PL_C::AddIR(class UUserWidget* UsageMenu)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "AddIR");

	Params::BP_DBAL_PL_C_AddIR Parms{};

	Parms.UsageMenu = UsageMenu;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.OnSelected_IR_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DBAL_PL_C::OnSelected_IR_Event(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "OnSelected_IR_Event");

	Params::BP_DBAL_PL_C_OnSelected_IR_Event Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.AddVIS
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      UsageMenu                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DBAL_PL_C::AddVIS(class UUserWidget* UsageMenu)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "AddVIS");

	Params::BP_DBAL_PL_C_AddVIS Parms{};

	Parms.UsageMenu = UsageMenu;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.OnSelected_VIS_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DBAL_PL_C::OnSelected_VIS_Event(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "OnSelected_VIS_Event");

	Params::BP_DBAL_PL_C_OnSelected_VIS_Event Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.OnBeingEquipped
// (Event, Public, BlueprintEvent)

void ABP_DBAL_PL_C::OnBeingEquipped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "OnBeingEquipped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.OnRemovedFromInventoryEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// class AGBCharacter*                     Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DBAL_PL_C::OnRemovedFromInventoryEvent(class AGBCharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "OnRemovedFromInventoryEvent");

	Params::BP_DBAL_PL_C_OnRemovedFromInventoryEvent Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.OnAddedToInventoryEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// class AGBCharacter*                     Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DBAL_PL_C::OnAddedToInventoryEvent(class AGBCharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "OnAddedToInventoryEvent");

	Params::BP_DBAL_PL_C_OnAddedToInventoryEvent Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.AddAttachedUseMenuEntries
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      UsageMenu                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DBAL_PL_C::AddAttachedUseMenuEntries(class UUserWidget* UsageMenu)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "AddAttachedUseMenuEntries");

	Params::BP_DBAL_PL_C_AddAttachedUseMenuEntries Parms{};

	Parms.UsageMenu = UsageMenu;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DBAL_PL.BP_DBAL_PL_C.AllowUsageWhileAttached
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABP_DBAL_PL_C::AllowUsageWhileAttached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DBAL_PL_C", "AllowUsageWhileAttached");

	Params::BP_DBAL_PL_C_AllowUsageWhileAttached Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

