#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Drag_PlatformPouch

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GroundBranch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Drag_PlatformPouch.BP_Drag_PlatformPouch_C
// 0x0018 (0x00C8 - 0x00B0)
class UBP_Drag_PlatformPouch_C final : public UGBInvItemDragDropOperation
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class FName>                           TargetSocketPrefixes;                              // 0x00B8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_BP_Drag_PlatformPouch(int32 EntryPoint);
	void OnLoadAssetsCompleteDelegate_Event_0(class UGBInvItemDragDropPayloadBase* GBInvItemDragDropPayloadBase);
	void Init();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Drag_PlatformPouch_C">();
	}
	static class UBP_Drag_PlatformPouch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Drag_PlatformPouch_C>();
	}
};
static_assert(alignof(UBP_Drag_PlatformPouch_C) == 0x000008, "Wrong alignment on UBP_Drag_PlatformPouch_C");
static_assert(sizeof(UBP_Drag_PlatformPouch_C) == 0x0000C8, "Wrong size on UBP_Drag_PlatformPouch_C");
static_assert(offsetof(UBP_Drag_PlatformPouch_C, UberGraphFrame) == 0x0000B0, "Member 'UBP_Drag_PlatformPouch_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_Drag_PlatformPouch_C, TargetSocketPrefixes) == 0x0000B8, "Member 'UBP_Drag_PlatformPouch_C::TargetSocketPrefixes' has a wrong offset!");

}

