#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Explosion_Dud

#include "Basic.hpp"

#include "BP_Explosion_Dud_classes.hpp"
#include "BP_Explosion_Dud_parameters.hpp"


namespace SDK
{

// Function BP_Explosion_Dud.BP_Explosion_Dud_C.ExecuteUbergraph_BP_Explosion_Dud
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Explosion_Dud_C::ExecuteUbergraph_BP_Explosion_Dud(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Explosion_Dud_C", "ExecuteUbergraph_BP_Explosion_Dud");

	Params::BP_Explosion_Dud_C_ExecuteUbergraph_BP_Explosion_Dud Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Explosion_Dud.BP_Explosion_Dud_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Explosion_Dud_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Explosion_Dud_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

