#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Footstep_Water

#include "Basic.hpp"

#include "BP_Footstep_Water_classes.hpp"
#include "BP_Footstep_Water_parameters.hpp"


namespace SDK
{

// Function BP_Footstep_Water.BP_Footstep_Water_C.ExecuteUbergraph_BP_Footstep_Water
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Footstep_Water_C::ExecuteUbergraph_BP_Footstep_Water(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Footstep_Water_C", "ExecuteUbergraph_BP_Footstep_Water");

	Params::BP_Footstep_Water_C_ExecuteUbergraph_BP_Footstep_Water Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Footstep_Water.BP_Footstep_Water_C.DebugFootstep
// (BlueprintCallable, BlueprintEvent)

void ABP_Footstep_Water_C::DebugFootstep()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Footstep_Water_C", "DebugFootstep");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Footstep_Water.BP_Footstep_Water_C.GetMaterialSwitch
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString ABP_Footstep_Water_C::GetMaterialSwitch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Footstep_Water_C", "GetMaterialSwitch");

	Params::BP_Footstep_Water_C_GetMaterialSwitch Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

