#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_G3A3

#include "Basic.hpp"

#include "BP_G3_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_G3A3.BP_G3A3_C
// 0x0010 (0x05B8 - 0x05A8)
class ABP_G3A3_C final : public ABP_G3_Master_C
{
public:
	class UGBSightComponent*                      IronSight;                                         // 0x05A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGBFrontSightPostComponent*             FrontSightPost;                                    // 0x05B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_G3A3_C">();
	}
	static class ABP_G3A3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_G3A3_C>();
	}
};
static_assert(alignof(ABP_G3A3_C) == 0x000008, "Wrong alignment on ABP_G3A3_C");
static_assert(sizeof(ABP_G3A3_C) == 0x0005B8, "Wrong size on ABP_G3A3_C");
static_assert(offsetof(ABP_G3A3_C, IronSight) == 0x0005A8, "Member 'ABP_G3A3_C::IronSight' has a wrong offset!");
static_assert(offsetof(ABP_G3A3_C, FrontSightPost) == 0x0005B0, "Member 'ABP_G3A3_C::FrontSightPost' has a wrong offset!");

}

