#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GBSkyLight

#include "Basic.hpp"

#include "FGBSkyLightSettings_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "GroundBranch_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GBSkyLight.BP_GBSkyLight_C
// 0x0110 (0x0340 - 0x0230)
class ABP_GBSkyLight_C final : public ASkyLight
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0230(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TMap<class FName, struct FFGBSkyLightSettings> SkyLightSettings;                                 // 0x0238(0x0050)(Edit, BlueprintVisible)
	struct FFGBSkyLightSettings                   DefaultSkyLightSettings;                           // 0x0288(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_GBSkyActor_C*                       GBSkyRef;                                          // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGBBlendedTimeSpan                     CurrentBlendedTimeSpawn;                           // 0x02C0(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	uint8                                         Pad_2D4[0x4];                                      // 0x02D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFGBSkyLightSettings                   CurrentSkyLightSettings;                           // 0x02D8(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFGBSkyLightSettings                   NextSkyLightSettings;                              // 0x0308(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bOverrideTOD;                                      // 0x0338(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_GBSkyLight(int32 EntryPoint);
	void ShouldOverrideTOD(bool bOverride);
	void OnTimeSpanChanged_Event_0(class FName Timespan);
	void BindToSkyActor();
	void ReceiveBeginPlay();
	void UserConstructionScript();
	void GetBlendedSkyLightSettings(struct FFGBSkyLightSettings* BlendedSkyLightSettings);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GBSkyLight_C">();
	}
	static class ABP_GBSkyLight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GBSkyLight_C>();
	}
};
static_assert(alignof(ABP_GBSkyLight_C) == 0x000008, "Wrong alignment on ABP_GBSkyLight_C");
static_assert(sizeof(ABP_GBSkyLight_C) == 0x000340, "Wrong size on ABP_GBSkyLight_C");
static_assert(offsetof(ABP_GBSkyLight_C, UberGraphFrame) == 0x000230, "Member 'ABP_GBSkyLight_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_GBSkyLight_C, SkyLightSettings) == 0x000238, "Member 'ABP_GBSkyLight_C::SkyLightSettings' has a wrong offset!");
static_assert(offsetof(ABP_GBSkyLight_C, DefaultSkyLightSettings) == 0x000288, "Member 'ABP_GBSkyLight_C::DefaultSkyLightSettings' has a wrong offset!");
static_assert(offsetof(ABP_GBSkyLight_C, GBSkyRef) == 0x0002B8, "Member 'ABP_GBSkyLight_C::GBSkyRef' has a wrong offset!");
static_assert(offsetof(ABP_GBSkyLight_C, CurrentBlendedTimeSpawn) == 0x0002C0, "Member 'ABP_GBSkyLight_C::CurrentBlendedTimeSpawn' has a wrong offset!");
static_assert(offsetof(ABP_GBSkyLight_C, CurrentSkyLightSettings) == 0x0002D8, "Member 'ABP_GBSkyLight_C::CurrentSkyLightSettings' has a wrong offset!");
static_assert(offsetof(ABP_GBSkyLight_C, NextSkyLightSettings) == 0x000308, "Member 'ABP_GBSkyLight_C::NextSkyLightSettings' has a wrong offset!");
static_assert(offsetof(ABP_GBSkyLight_C, bOverrideTOD) == 0x000338, "Member 'ABP_GBSkyLight_C::bOverrideTOD' has a wrong offset!");

}

