#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GBLadder

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_GBLadder.BP_GBLadder_C.UserConstructionScript
// 0x0080 (0x0080 - 0x0000)
struct BP_GBLadder_C_UserConstructionScript final
{
public:
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_1;                // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0020(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_1;              // 0x0050(0x0030)(IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_GBLadder_C_UserConstructionScript) == 0x000010, "Wrong alignment on BP_GBLadder_C_UserConstructionScript");
static_assert(sizeof(BP_GBLadder_C_UserConstructionScript) == 0x000080, "Wrong size on BP_GBLadder_C_UserConstructionScript");
static_assert(offsetof(BP_GBLadder_C_UserConstructionScript, CallFunc_MakeRotator_ReturnValue) == 0x000000, "Member 'BP_GBLadder_C_UserConstructionScript::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_UserConstructionScript, CallFunc_MakeRotator_ReturnValue_1) == 0x00000C, "Member 'BP_GBLadder_C_UserConstructionScript::CallFunc_MakeRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_UserConstructionScript, CallFunc_MakeTransform_ReturnValue) == 0x000020, "Member 'BP_GBLadder_C_UserConstructionScript::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_UserConstructionScript, CallFunc_MakeTransform_ReturnValue_1) == 0x000050, "Member 'BP_GBLadder_C_UserConstructionScript::CallFunc_MakeTransform_ReturnValue_1' has a wrong offset!");

// Function BP_GBLadder.BP_GBLadder_C.ResetKytNavLinks
// 0x0080 (0x0080 - 0x0000)
struct BP_GBLadder_C_ResetKytNavLinks final
{
public:
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_1;                // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0020(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_1;              // 0x0050(0x0030)(IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_GBLadder_C_ResetKytNavLinks) == 0x000010, "Wrong alignment on BP_GBLadder_C_ResetKytNavLinks");
static_assert(sizeof(BP_GBLadder_C_ResetKytNavLinks) == 0x000080, "Wrong size on BP_GBLadder_C_ResetKytNavLinks");
static_assert(offsetof(BP_GBLadder_C_ResetKytNavLinks, CallFunc_MakeRotator_ReturnValue) == 0x000000, "Member 'BP_GBLadder_C_ResetKytNavLinks::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_ResetKytNavLinks, CallFunc_MakeRotator_ReturnValue_1) == 0x00000C, "Member 'BP_GBLadder_C_ResetKytNavLinks::CallFunc_MakeRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_ResetKytNavLinks, CallFunc_MakeTransform_ReturnValue) == 0x000020, "Member 'BP_GBLadder_C_ResetKytNavLinks::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_ResetKytNavLinks, CallFunc_MakeTransform_ReturnValue_1) == 0x000050, "Member 'BP_GBLadder_C_ResetKytNavLinks::CallFunc_MakeTransform_ReturnValue_1' has a wrong offset!");

// Function BP_GBLadder.BP_GBLadder_C.GetTopLocationWS
// 0x0080 (0x0080 - 0x0000)
struct BP_GBLadder_C_GetTopLocationWS final
{
public:
	struct FVector                                TopLocation;                                       // 0x0000(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0xC];                                       // 0x0024(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0030(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_TransformDirection_ReturnValue;           // 0x0060(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x006C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GBLadder_C_GetTopLocationWS) == 0x000010, "Wrong alignment on BP_GBLadder_C_GetTopLocationWS");
static_assert(sizeof(BP_GBLadder_C_GetTopLocationWS) == 0x000080, "Wrong size on BP_GBLadder_C_GetTopLocationWS");
static_assert(offsetof(BP_GBLadder_C_GetTopLocationWS, TopLocation) == 0x000000, "Member 'BP_GBLadder_C_GetTopLocationWS::TopLocation' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_GetTopLocationWS, CallFunc_K2_GetActorRotation_ReturnValue) == 0x00000C, "Member 'BP_GBLadder_C_GetTopLocationWS::CallFunc_K2_GetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_GetTopLocationWS, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000018, "Member 'BP_GBLadder_C_GetTopLocationWS::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_GetTopLocationWS, CallFunc_MakeTransform_ReturnValue) == 0x000030, "Member 'BP_GBLadder_C_GetTopLocationWS::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_GetTopLocationWS, CallFunc_TransformDirection_ReturnValue) == 0x000060, "Member 'BP_GBLadder_C_GetTopLocationWS::CallFunc_TransformDirection_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_GetTopLocationWS, CallFunc_Add_VectorVector_ReturnValue) == 0x00006C, "Member 'BP_GBLadder_C_GetTopLocationWS::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");

// Function BP_GBLadder.BP_GBLadder_C.GetBotLocationWS
// 0x0080 (0x0080 - 0x0000)
struct BP_GBLadder_C_GetBotLocationWS final
{
public:
	struct FVector                                TopLocation;                                       // 0x0000(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0xC];                                       // 0x0024(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0030(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_TransformDirection_ReturnValue;           // 0x0060(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x006C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GBLadder_C_GetBotLocationWS) == 0x000010, "Wrong alignment on BP_GBLadder_C_GetBotLocationWS");
static_assert(sizeof(BP_GBLadder_C_GetBotLocationWS) == 0x000080, "Wrong size on BP_GBLadder_C_GetBotLocationWS");
static_assert(offsetof(BP_GBLadder_C_GetBotLocationWS, TopLocation) == 0x000000, "Member 'BP_GBLadder_C_GetBotLocationWS::TopLocation' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_GetBotLocationWS, CallFunc_K2_GetActorRotation_ReturnValue) == 0x00000C, "Member 'BP_GBLadder_C_GetBotLocationWS::CallFunc_K2_GetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_GetBotLocationWS, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000018, "Member 'BP_GBLadder_C_GetBotLocationWS::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_GetBotLocationWS, CallFunc_MakeTransform_ReturnValue) == 0x000030, "Member 'BP_GBLadder_C_GetBotLocationWS::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_GetBotLocationWS, CallFunc_TransformDirection_ReturnValue) == 0x000060, "Member 'BP_GBLadder_C_GetBotLocationWS::CallFunc_TransformDirection_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GBLadder_C_GetBotLocationWS, CallFunc_Add_VectorVector_ReturnValue) == 0x00006C, "Member 'BP_GBLadder_C_GetBotLocationWS::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");

}

