#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OldPickup

#include "Basic.hpp"

#include "BP_OldPickup_classes.hpp"
#include "BP_OldPickup_parameters.hpp"


namespace SDK
{

// Function BP_OldPickup.BP_OldPickup_C.ExecuteUbergraph_BP_OldPickup
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_OldPickup_C::ExecuteUbergraph_BP_OldPickup(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_OldPickup_C", "ExecuteUbergraph_BP_OldPickup");

	Params::BP_OldPickup_C_ExecuteUbergraph_BP_OldPickup Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_OldPickup.BP_OldPickup_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_OldPickup_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_OldPickup_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_OldPickup.BP_OldPickup_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_OldPickup_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_OldPickup_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

