#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ServerInfoBoard

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GroundBranch_structs.hpp"


namespace SDK::Params
{

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.ExecuteUbergraph_BP_ServerInfoBoard
// 0x0440 (0x0440 - 0x0000)
struct BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_DialogueBox_C*                     CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable;                              // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBGameState*                           K2Node_DynamicCast_AsGBGame_State;                 // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     K2Node_DynamicCast_AsMaterial_Interface;           // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue_1;               // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBGameState*                           K2Node_DynamicCast_AsGBGame_State_1;               // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue_2;               // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGBServerBasicInfo                     CallFunc_GetServerBasicInfo_ReturnValue;           // 0x0078(0x0030)()
	class AGBGameState*                           K2Node_DynamicCast_AsGBGame_State_2;               // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGBServerBasicInfo                     CallFunc_GetServerBasicInfo_ReturnValue_1;         // 0x00B8(0x0030)()
	class UObject*                                K2Node_CustomEvent_Loaded_4;                       // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue_3;               // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue_4;               // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBGameState*                           K2Node_DynamicCast_AsGBGame_State_3;               // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBGameState*                           K2Node_DynamicCast_AsGBGame_State_4;               // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGBServerBasicInfo                     CallFunc_GetServerBasicInfo_ReturnValue_2;         // 0x0120(0x0030)()
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_151[0x7];                                      // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue_5;               // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBGameState*                           K2Node_DynamicCast_AsGBGame_State_5;               // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_171[0x7];                                      // 0x0171(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBPlayerController*                    K2Node_DynamicCast_AsGBPlayer_Controller;          // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGBServerBasicInfo                     CallFunc_GetServerBasicInfo_ReturnValue_3;         // 0x0188(0x0030)()
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue_6;               // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Temp_class_Variable;                               // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBGameState*                           K2Node_DynamicCast_AsGBGame_State_6;               // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D9[0x7];                                      // 0x01D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_ClassDynamicCast_AsWBP_Server_Info_Board_MOTD; // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1EA[0x6];                                      // 0x01EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_ServerInfoBoard_MOTD_C*            CallFunc_Create_ReturnValue_1;                     // 0x01F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UObject>                    K2Node_CustomEvent_Loaded_5;                       // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBPlayerController*                    K2Node_DynamicCast_AsGBPlayer_Controller_1;        // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_9;                     // 0x0210(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0211(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_212[0x6];                                      // 0x0212(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_DialogueBox_C*                     K2Node_CustomEvent_dialogue;                       // 0x0218(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetEmptyText_ReturnValue;                 // 0x0220(0x0018)()
	bool                                          CallFunc_Config_GetArray_bValid;                   // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_239[0x7];                                      // 0x0239(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         CallFunc_Config_GetArray_ReturnValue;              // 0x0240(0x0010)(ReferenceParm)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0251(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_252[0x6];                                      // 0x0252(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABP_ServerInfoBoard_C*>          CallFunc_GetAllActorsOfClass_OutActors;            // 0x0258(0x0010)(ReferenceParm)
	class ABP_ServerInfoBoard_C*                  CallFunc_Array_Get_Item;                           // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0270(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0274(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_275[0x3];                                      // 0x0275(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABP_ServerInfoBoard_C*>          CallFunc_GetAllActorsOfClass_OutActors_1;          // 0x0278(0x0010)(ReferenceParm)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate;              // 0x0288(0x0010)(ZeroConstructor, NoDestructor)
	class ABP_ServerInfoBoard_C*                  CallFunc_Array_Get_Item_1;                         // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x02A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x02A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_bIsChecked;                     // 0x02A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Config_GetArray_bValid_1;                 // 0x02A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A7[0x1];                                      // 0x02A7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         CallFunc_Config_GetArray_ReturnValue_1;            // 0x02A8(0x0010)(ReferenceParm)
	bool                                          CallFunc_Array_Contains_ReturnValue_1;             // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x02B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x02BA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BB[0x1];                                      // 0x02BB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(TSubclassOf<class UObject> Loaded)> K2Node_CreateDelegate_OutputDelegate_1;       // 0x02BC(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_2CC[0x4];                                      // 0x02CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_ServerInfoBoard_C*                  CallFunc_GetActorOfClass_ReturnValue;              // 0x02D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBGameState*                           K2Node_CustomEvent_GameState;                      // 0x02D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x02E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E1[0x7];                                      // 0x02E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGBServerBasicInfo                     CallFunc_GetServerBasicInfo_ReturnValue_4;         // 0x02E8(0x0030)()
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x0318(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_319[0x3];                                      // 0x0319(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate_2;            // 0x031C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x032C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32D[0x3];                                      // 0x032D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(TSubclassOf<class UObject> Loaded)> K2Node_CreateDelegate_OutputDelegate_3;       // 0x0330(0x0010)(ZeroConstructor, NoDestructor)
	class UObject*                                Temp_object_Variable_1;                            // 0x0340(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                K2Node_CustomEvent_Loaded;                         // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     K2Node_DynamicCast_AsMaterial_Interface_1;         // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_10;                    // 0x0358(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_359[0x7];                                      // 0x0359(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 Temp_class_Variable_1;                             // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UObject>                    K2Node_CustomEvent_Loaded_1;                       // 0x0368(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsWBP_Server_Info_Board_Stand_Alone; // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_1;                // 0x0378(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_379[0x7];                                      // 0x0379(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_ServerInfoBoard_StandAlone_C*      CallFunc_Create_ReturnValue_2;                     // 0x0380(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class AGBGameState* GameState)> K2Node_CreateDelegate_OutputDelegate_4;           // 0x0388(0x0010)(ZeroConstructor, NoDestructor)
	class UObject*                                Temp_object_Variable_2;                            // 0x0398(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     K2Node_DynamicCast_AsMaterial_Interface_2;         // 0x03A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_11;                    // 0x03A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3A9[0x7];                                      // 0x03A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded_2;                       // 0x03B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsStandalone_ReturnValue;                 // 0x03B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3B9[0x3];                                      // 0x03B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate_5;            // 0x03BC(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(TSubclassOf<class UObject> Loaded)> K2Node_CreateDelegate_OutputDelegate_6;       // 0x03CC(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(bool bIsChecked)>              K2Node_CreateDelegate_OutputDelegate_7;            // 0x03DC(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x03EC(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_3FC[0x4];                                      // 0x03FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 Temp_class_Variable_2;                             // 0x0400(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsWBP_Server_Info_Board_Web_Banner; // 0x0408(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_2;                // 0x0410(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_411[0x7];                                      // 0x0411(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_ServerInfoBoard_WebBanner_C*       CallFunc_Create_ReturnValue_3;                     // 0x0418(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UObject>                    K2Node_CustomEvent_Loaded_3;                       // 0x0420(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UWBP_ServerWebBanner_Warning_C*         CallFunc_Create_ReturnValue_4;                     // 0x0428(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UWBP_DialogueBox_C* Dialogue)> K2Node_CreateDelegate_OutputDelegate_9;      // 0x0430(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard) == 0x000008, "Wrong alignment on BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard");
static_assert(sizeof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard) == 0x000440, "Wrong size on BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, EntryPoint) == 0x000000, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Create_ReturnValue) == 0x000008, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, Temp_int_Loop_Counter_Variable_1) == 0x000014, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Add_IntInt_ReturnValue_1) == 0x00001C, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, Temp_int_Array_Index_Variable) == 0x000020, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, Temp_int_Array_Index_Variable_1) == 0x000024, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetGameState_ReturnValue) == 0x000028, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, Temp_object_Variable) == 0x000030, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsGBGame_State) == 0x000038, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsGBGame_State' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsMaterial_Interface) == 0x000048, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsMaterial_Interface' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_IsValid_ReturnValue) == 0x000051, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetGameState_ReturnValue_1) == 0x000058, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetGameState_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsGBGame_State_1) == 0x000060, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsGBGame_State_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_2) == 0x000068, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetGameState_ReturnValue_2) == 0x000070, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetGameState_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetServerBasicInfo_ReturnValue) == 0x000078, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetServerBasicInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsGBGame_State_2) == 0x0000A8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsGBGame_State_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_3) == 0x0000B0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetServerBasicInfo_ReturnValue_1) == 0x0000B8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetServerBasicInfo_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CustomEvent_Loaded_4) == 0x0000E8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CustomEvent_Loaded_4' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetGameState_ReturnValue_3) == 0x0000F0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetGameState_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetGameState_ReturnValue_4) == 0x0000F8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetGameState_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsGBGame_State_3) == 0x000100, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsGBGame_State_3' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_4) == 0x000108, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsGBGame_State_4) == 0x000110, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsGBGame_State_4' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_5) == 0x000118, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetServerBasicInfo_ReturnValue_2) == 0x000120, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetServerBasicInfo_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_IsValidClass_ReturnValue) == 0x000150, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetGameState_ReturnValue_5) == 0x000158, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetGameState_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetPlayerController_ReturnValue) == 0x000160, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsGBGame_State_5) == 0x000168, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsGBGame_State_5' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_6) == 0x000170, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsGBPlayer_Controller) == 0x000178, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsGBPlayer_Controller' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_7) == 0x000180, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetServerBasicInfo_ReturnValue_3) == 0x000188, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetServerBasicInfo_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_IsValid_ReturnValue_1) == 0x0001B8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetGameState_ReturnValue_6) == 0x0001C0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetGameState_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, Temp_class_Variable) == 0x0001C8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::Temp_class_Variable' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsGBGame_State_6) == 0x0001D0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsGBGame_State_6' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_8) == 0x0001D8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_ClassDynamicCast_AsWBP_Server_Info_Board_MOTD) == 0x0001E0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_ClassDynamicCast_AsWBP_Server_Info_Board_MOTD' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_ClassDynamicCast_bSuccess) == 0x0001E8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_IsValid_ReturnValue_2) == 0x0001E9, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Create_ReturnValue_1) == 0x0001F0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CustomEvent_Loaded_5) == 0x0001F8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CustomEvent_Loaded_5' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetPlayerController_ReturnValue_1) == 0x000200, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsGBPlayer_Controller_1) == 0x000208, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsGBPlayer_Controller_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_9) == 0x000210, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_9' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_IsDedicatedServer_ReturnValue) == 0x000211, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CustomEvent_dialogue) == 0x000218, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CustomEvent_dialogue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetEmptyText_ReturnValue) == 0x000220, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetEmptyText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Config_GetArray_bValid) == 0x000238, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Config_GetArray_bValid' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Config_GetArray_ReturnValue) == 0x000240, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Config_GetArray_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Array_Contains_ReturnValue) == 0x000250, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_BooleanAND_ReturnValue) == 0x000251, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetAllActorsOfClass_OutActors) == 0x000258, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Array_Get_Item) == 0x000268, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Array_Length_ReturnValue) == 0x000270, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Less_IntInt_ReturnValue) == 0x000274, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetAllActorsOfClass_OutActors_1) == 0x000278, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetAllActorsOfClass_OutActors_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CreateDelegate_OutputDelegate) == 0x000288, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Array_Get_Item_1) == 0x000298, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Array_Length_ReturnValue_1) == 0x0002A0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Less_IntInt_ReturnValue_1) == 0x0002A4, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CustomEvent_bIsChecked) == 0x0002A5, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CustomEvent_bIsChecked' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Config_GetArray_bValid_1) == 0x0002A6, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Config_GetArray_bValid_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Config_GetArray_ReturnValue_1) == 0x0002A8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Config_GetArray_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Array_Contains_ReturnValue_1) == 0x0002B8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Array_Contains_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_BooleanAND_ReturnValue_1) == 0x0002B9, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_Event_EndPlayReason) == 0x0002BA, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_Event_EndPlayReason' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CreateDelegate_OutputDelegate_1) == 0x0002BC, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetActorOfClass_ReturnValue) == 0x0002D0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetActorOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CustomEvent_GameState) == 0x0002D8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CustomEvent_GameState' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0002E0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_GetServerBasicInfo_ReturnValue_4) == 0x0002E8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_GetServerBasicInfo_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_IsEmpty_ReturnValue) == 0x000318, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CreateDelegate_OutputDelegate_2) == 0x00031C, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_MakeLiteralByte_ReturnValue) == 0x00032C, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CreateDelegate_OutputDelegate_3) == 0x000330, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, Temp_object_Variable_1) == 0x000340, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CustomEvent_Loaded) == 0x000348, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsMaterial_Interface_1) == 0x000350, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsMaterial_Interface_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_10) == 0x000358, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_10' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, Temp_class_Variable_1) == 0x000360, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::Temp_class_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CustomEvent_Loaded_1) == 0x000368, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CustomEvent_Loaded_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_ClassDynamicCast_AsWBP_Server_Info_Board_Stand_Alone) == 0x000370, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_ClassDynamicCast_AsWBP_Server_Info_Board_Stand_Alone' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_ClassDynamicCast_bSuccess_1) == 0x000378, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_ClassDynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Create_ReturnValue_2) == 0x000380, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Create_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CreateDelegate_OutputDelegate_4) == 0x000388, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, Temp_object_Variable_2) == 0x000398, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_AsMaterial_Interface_2) == 0x0003A0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_AsMaterial_Interface_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_DynamicCast_bSuccess_11) == 0x0003A8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_DynamicCast_bSuccess_11' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CustomEvent_Loaded_2) == 0x0003B0, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CustomEvent_Loaded_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_IsStandalone_ReturnValue) == 0x0003B8, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_IsStandalone_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CreateDelegate_OutputDelegate_5) == 0x0003BC, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CreateDelegate_OutputDelegate_6) == 0x0003CC, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CreateDelegate_OutputDelegate_7) == 0x0003DC, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CreateDelegate_OutputDelegate_8) == 0x0003EC, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, Temp_class_Variable_2) == 0x000400, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::Temp_class_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_ClassDynamicCast_AsWBP_Server_Info_Board_Web_Banner) == 0x000408, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_ClassDynamicCast_AsWBP_Server_Info_Board_Web_Banner' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_ClassDynamicCast_bSuccess_2) == 0x000410, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_ClassDynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Create_ReturnValue_3) == 0x000418, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Create_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CustomEvent_Loaded_3) == 0x000420, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CustomEvent_Loaded_3' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, CallFunc_Create_ReturnValue_4) == 0x000428, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::CallFunc_Create_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard, K2Node_CreateDelegate_OutputDelegate_9) == 0x000430, "Member 'BP_ServerInfoBoard_C_ExecuteUbergraph_BP_ServerInfoBoard::K2Node_CreateDelegate_OutputDelegate_9' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.OnServerBasicInfoUpdatedEvent_Event_0
// 0x0008 (0x0008 - 0x0000)
struct BP_ServerInfoBoard_C_OnServerBasicInfoUpdatedEvent_Event_0 final
{
public:
	class AGBGameState*                           GameState;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ServerInfoBoard_C_OnServerBasicInfoUpdatedEvent_Event_0) == 0x000008, "Wrong alignment on BP_ServerInfoBoard_C_OnServerBasicInfoUpdatedEvent_Event_0");
static_assert(sizeof(BP_ServerInfoBoard_C_OnServerBasicInfoUpdatedEvent_Event_0) == 0x000008, "Wrong size on BP_ServerInfoBoard_C_OnServerBasicInfoUpdatedEvent_Event_0");
static_assert(offsetof(BP_ServerInfoBoard_C_OnServerBasicInfoUpdatedEvent_Event_0, GameState) == 0x000000, "Member 'BP_ServerInfoBoard_C_OnServerBasicInfoUpdatedEvent_Event_0::GameState' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct BP_ServerInfoBoard_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ServerInfoBoard_C_ReceiveEndPlay) == 0x000001, "Wrong alignment on BP_ServerInfoBoard_C_ReceiveEndPlay");
static_assert(sizeof(BP_ServerInfoBoard_C_ReceiveEndPlay) == 0x000001, "Wrong size on BP_ServerInfoBoard_C_ReceiveEndPlay");
static_assert(offsetof(BP_ServerInfoBoard_C_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'BP_ServerInfoBoard_C_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.OnCheckStateChanged_Event_0
// 0x0001 (0x0001 - 0x0000)
struct BP_ServerInfoBoard_C_OnCheckStateChanged_Event_0 final
{
public:
	bool                                          bIsChecked;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_ServerInfoBoard_C_OnCheckStateChanged_Event_0) == 0x000001, "Wrong alignment on BP_ServerInfoBoard_C_OnCheckStateChanged_Event_0");
static_assert(sizeof(BP_ServerInfoBoard_C_OnCheckStateChanged_Event_0) == 0x000001, "Wrong size on BP_ServerInfoBoard_C_OnCheckStateChanged_Event_0");
static_assert(offsetof(BP_ServerInfoBoard_C_OnCheckStateChanged_Event_0, bIsChecked) == 0x000000, "Member 'BP_ServerInfoBoard_C_OnCheckStateChanged_Event_0::bIsChecked' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.OnOkClicked_Event_0
// 0x0008 (0x0008 - 0x0000)
struct BP_ServerInfoBoard_C_OnOkClicked_Event_0 final
{
public:
	class UWBP_DialogueBox_C*                     Dialogue;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ServerInfoBoard_C_OnOkClicked_Event_0) == 0x000008, "Wrong alignment on BP_ServerInfoBoard_C_OnOkClicked_Event_0");
static_assert(sizeof(BP_ServerInfoBoard_C_OnOkClicked_Event_0) == 0x000008, "Wrong size on BP_ServerInfoBoard_C_OnOkClicked_Event_0");
static_assert(offsetof(BP_ServerInfoBoard_C_OnOkClicked_Event_0, Dialogue) == 0x000000, "Member 'BP_ServerInfoBoard_C_OnOkClicked_Event_0::Dialogue' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.OnLoaded_8CB09EC123CB4644A611EEBB19ABCD08
// 0x0008 (0x0008 - 0x0000)
struct BP_ServerInfoBoard_C_OnLoaded_8CB09EC123CB4644A611EEBB19ABCD08 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ServerInfoBoard_C_OnLoaded_8CB09EC123CB4644A611EEBB19ABCD08) == 0x000008, "Wrong alignment on BP_ServerInfoBoard_C_OnLoaded_8CB09EC123CB4644A611EEBB19ABCD08");
static_assert(sizeof(BP_ServerInfoBoard_C_OnLoaded_8CB09EC123CB4644A611EEBB19ABCD08) == 0x000008, "Wrong size on BP_ServerInfoBoard_C_OnLoaded_8CB09EC123CB4644A611EEBB19ABCD08");
static_assert(offsetof(BP_ServerInfoBoard_C_OnLoaded_8CB09EC123CB4644A611EEBB19ABCD08, Loaded) == 0x000000, "Member 'BP_ServerInfoBoard_C_OnLoaded_8CB09EC123CB4644A611EEBB19ABCD08::Loaded' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.OnLoaded_848816D332324B988E51451DEE28150E
// 0x0008 (0x0008 - 0x0000)
struct BP_ServerInfoBoard_C_OnLoaded_848816D332324B988E51451DEE28150E final
{
public:
	TSubclassOf<class UObject>                    Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(BP_ServerInfoBoard_C_OnLoaded_848816D332324B988E51451DEE28150E) == 0x000008, "Wrong alignment on BP_ServerInfoBoard_C_OnLoaded_848816D332324B988E51451DEE28150E");
static_assert(sizeof(BP_ServerInfoBoard_C_OnLoaded_848816D332324B988E51451DEE28150E) == 0x000008, "Wrong size on BP_ServerInfoBoard_C_OnLoaded_848816D332324B988E51451DEE28150E");
static_assert(offsetof(BP_ServerInfoBoard_C_OnLoaded_848816D332324B988E51451DEE28150E, Loaded) == 0x000000, "Member 'BP_ServerInfoBoard_C_OnLoaded_848816D332324B988E51451DEE28150E::Loaded' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.OnLoaded_118FBDAC4ACBDBF9750EF18DF588C93A
// 0x0008 (0x0008 - 0x0000)
struct BP_ServerInfoBoard_C_OnLoaded_118FBDAC4ACBDBF9750EF18DF588C93A final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ServerInfoBoard_C_OnLoaded_118FBDAC4ACBDBF9750EF18DF588C93A) == 0x000008, "Wrong alignment on BP_ServerInfoBoard_C_OnLoaded_118FBDAC4ACBDBF9750EF18DF588C93A");
static_assert(sizeof(BP_ServerInfoBoard_C_OnLoaded_118FBDAC4ACBDBF9750EF18DF588C93A) == 0x000008, "Wrong size on BP_ServerInfoBoard_C_OnLoaded_118FBDAC4ACBDBF9750EF18DF588C93A");
static_assert(offsetof(BP_ServerInfoBoard_C_OnLoaded_118FBDAC4ACBDBF9750EF18DF588C93A, Loaded) == 0x000000, "Member 'BP_ServerInfoBoard_C_OnLoaded_118FBDAC4ACBDBF9750EF18DF588C93A::Loaded' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.OnLoaded_CA19DF774F88B6A4D76DFB84241E4046
// 0x0008 (0x0008 - 0x0000)
struct BP_ServerInfoBoard_C_OnLoaded_CA19DF774F88B6A4D76DFB84241E4046 final
{
public:
	TSubclassOf<class UObject>                    Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(BP_ServerInfoBoard_C_OnLoaded_CA19DF774F88B6A4D76DFB84241E4046) == 0x000008, "Wrong alignment on BP_ServerInfoBoard_C_OnLoaded_CA19DF774F88B6A4D76DFB84241E4046");
static_assert(sizeof(BP_ServerInfoBoard_C_OnLoaded_CA19DF774F88B6A4D76DFB84241E4046) == 0x000008, "Wrong size on BP_ServerInfoBoard_C_OnLoaded_CA19DF774F88B6A4D76DFB84241E4046");
static_assert(offsetof(BP_ServerInfoBoard_C_OnLoaded_CA19DF774F88B6A4D76DFB84241E4046, Loaded) == 0x000000, "Member 'BP_ServerInfoBoard_C_OnLoaded_CA19DF774F88B6A4D76DFB84241E4046::Loaded' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.OnLoaded_93EE469944C3512D064A8F914B956326
// 0x0008 (0x0008 - 0x0000)
struct BP_ServerInfoBoard_C_OnLoaded_93EE469944C3512D064A8F914B956326 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ServerInfoBoard_C_OnLoaded_93EE469944C3512D064A8F914B956326) == 0x000008, "Wrong alignment on BP_ServerInfoBoard_C_OnLoaded_93EE469944C3512D064A8F914B956326");
static_assert(sizeof(BP_ServerInfoBoard_C_OnLoaded_93EE469944C3512D064A8F914B956326) == 0x000008, "Wrong size on BP_ServerInfoBoard_C_OnLoaded_93EE469944C3512D064A8F914B956326");
static_assert(offsetof(BP_ServerInfoBoard_C_OnLoaded_93EE469944C3512D064A8F914B956326, Loaded) == 0x000000, "Member 'BP_ServerInfoBoard_C_OnLoaded_93EE469944C3512D064A8F914B956326::Loaded' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.OnLoaded_D1585AF64E81CBA3ABFFFEBAD7029A5F
// 0x0008 (0x0008 - 0x0000)
struct BP_ServerInfoBoard_C_OnLoaded_D1585AF64E81CBA3ABFFFEBAD7029A5F final
{
public:
	TSubclassOf<class UObject>                    Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(BP_ServerInfoBoard_C_OnLoaded_D1585AF64E81CBA3ABFFFEBAD7029A5F) == 0x000008, "Wrong alignment on BP_ServerInfoBoard_C_OnLoaded_D1585AF64E81CBA3ABFFFEBAD7029A5F");
static_assert(sizeof(BP_ServerInfoBoard_C_OnLoaded_D1585AF64E81CBA3ABFFFEBAD7029A5F) == 0x000008, "Wrong size on BP_ServerInfoBoard_C_OnLoaded_D1585AF64E81CBA3ABFFFEBAD7029A5F");
static_assert(offsetof(BP_ServerInfoBoard_C_OnLoaded_D1585AF64E81CBA3ABFFFEBAD7029A5F, Loaded) == 0x000000, "Member 'BP_ServerInfoBoard_C_OnLoaded_D1585AF64E81CBA3ABFFFEBAD7029A5F::Loaded' has a wrong offset!");

// Function BP_ServerInfoBoard.BP_ServerInfoBoard_C.IsMOTDWebBased
// 0x0018 (0x0018 - 0x0000)
struct BP_ServerInfoBoard_C_IsMOTDWebBased final
{
public:
	class FString                                 MOTD;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          IsMOTDWebBased_0;                                  // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_StartsWith_ReturnValue;                   // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_StartsWith_ReturnValue_1;                 // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_ServerInfoBoard_C_IsMOTDWebBased) == 0x000008, "Wrong alignment on BP_ServerInfoBoard_C_IsMOTDWebBased");
static_assert(sizeof(BP_ServerInfoBoard_C_IsMOTDWebBased) == 0x000018, "Wrong size on BP_ServerInfoBoard_C_IsMOTDWebBased");
static_assert(offsetof(BP_ServerInfoBoard_C_IsMOTDWebBased, MOTD) == 0x000000, "Member 'BP_ServerInfoBoard_C_IsMOTDWebBased::MOTD' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_IsMOTDWebBased, IsMOTDWebBased_0) == 0x000010, "Member 'BP_ServerInfoBoard_C_IsMOTDWebBased::IsMOTDWebBased_0' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_IsMOTDWebBased, CallFunc_StartsWith_ReturnValue) == 0x000011, "Member 'BP_ServerInfoBoard_C_IsMOTDWebBased::CallFunc_StartsWith_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_IsMOTDWebBased, CallFunc_StartsWith_ReturnValue_1) == 0x000012, "Member 'BP_ServerInfoBoard_C_IsMOTDWebBased::CallFunc_StartsWith_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ServerInfoBoard_C_IsMOTDWebBased, CallFunc_BooleanOR_ReturnValue) == 0x000013, "Member 'BP_ServerInfoBoard_C_IsMOTDWebBased::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

}

