#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Target_Drop

#include "Basic.hpp"

#include "BP_Target_Drop_classes.hpp"
#include "BP_Target_Drop_parameters.hpp"


namespace SDK
{

// Function BP_Target_Drop.BP_Target_Drop_C.ExecuteUbergraph_BP_Target_Drop
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Target_Drop_C::ExecuteUbergraph_BP_Target_Drop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "ExecuteUbergraph_BP_Target_Drop");

	Params::BP_Target_Drop_C_ExecuteUbergraph_BP_Target_Drop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Target_Drop.BP_Target_Drop_C.K2_OnReset
// (Event, Public, BlueprintEvent)

void ABP_Target_Drop_C::K2_OnReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "K2_OnReset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Target_Drop.BP_Target_Drop_C.RiseUp
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Target_Drop_C::RiseUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "RiseUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Target_Drop.BP_Target_Drop_C.BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_0_OnPlateSkinSet__DelegateSignature
// (BlueprintEvent)
// Parameters:
// TSoftObjectPtr<class UMaterialInterface>Skin                                                   (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// class UBP_PlateComponent_C*             PlateComponent                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Target_Drop_C::BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_0_OnPlateSkinSet__DelegateSignature(TSoftObjectPtr<class UMaterialInterface> Skin, class UBP_PlateComponent_C* PlateComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_0_OnPlateSkinSet__DelegateSignature");

	Params::BP_Target_Drop_C_BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_0_OnPlateSkinSet__DelegateSignature Parms{};

	Parms.Skin = Skin;
	Parms.PlateComponent = PlateComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Target_Drop.BP_Target_Drop_C.OnSkinLoaded_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          LoadedAsset                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Target_Drop_C::OnSkinLoaded_Event(class UObject* LoadedAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "OnSkinLoaded_Event");

	Params::BP_Target_Drop_C_OnSkinLoaded_Event Parms{};

	Parms.LoadedAsset = LoadedAsset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Target_Drop.BP_Target_Drop_C.BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_11_OnPlateReset__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBP_PlateComponent_C*             PlateComponent                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Target_Drop_C::BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_11_OnPlateReset__DelegateSignature(class UBP_PlateComponent_C* PlateComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_11_OnPlateReset__DelegateSignature");

	Params::BP_Target_Drop_C_BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_11_OnPlateReset__DelegateSignature Parms{};

	Parms.PlateComponent = PlateComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Target_Drop.BP_Target_Drop_C.StartSliding
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   ServerTime                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Target_Drop_C::StartSliding(float ServerTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "StartSliding");

	Params::BP_Target_Drop_C_StartSliding Parms{};

	Parms.ServerTime = ServerTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Target_Drop.BP_Target_Drop_C.DropDown
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Target_Drop_C::DropDown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "DropDown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Target_Drop.BP_Target_Drop_C.BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_0_OnPlateDropped__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBP_PlateComponent_C*             PlateComponent                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Target_Drop_C::BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_0_OnPlateDropped__DelegateSignature(class UBP_PlateComponent_C* PlateComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_0_OnPlateDropped__DelegateSignature");

	Params::BP_Target_Drop_C_BndEvt__BP_PlateComponent_K2Node_ComponentBoundEvent_0_OnPlateDropped__DelegateSignature Parms{};

	Parms.PlateComponent = PlateComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Target_Drop.BP_Target_Drop_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Target_Drop_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Target_Drop.BP_Target_Drop_C.DropPlateTimeline__UpdateFunc
// (BlueprintEvent)

void ABP_Target_Drop_C::DropPlateTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "DropPlateTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Target_Drop.BP_Target_Drop_C.DropPlateTimeline__FinishedFunc
// (BlueprintEvent)

void ABP_Target_Drop_C::DropPlateTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "DropPlateTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Target_Drop.BP_Target_Drop_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Target_Drop_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Target_Drop.BP_Target_Drop_C.OnRep_ReplicatedMaterial
// (BlueprintCallable, BlueprintEvent)

void ABP_Target_Drop_C::OnRep_ReplicatedMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Target_Drop_C", "OnRep_ReplicatedMaterial");

	UObject::ProcessEvent(Func, nullptr);
}

}

