#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CM_NVG_Master

#include "Basic.hpp"

#include "CM_NVG_Master_classes.hpp"
#include "CM_NVG_Master_parameters.hpp"


namespace SDK
{

// Function CM_NVG_Master.CM_NVG_Master_C.ExecuteUbergraph_CM_NVG_Master
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_NVG_Master_C::ExecuteUbergraph_CM_NVG_Master(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "ExecuteUbergraph_CM_NVG_Master");

	Params::CM_NVG_Master_C_ExecuteUbergraph_CM_NVG_Master Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_NVG_Master.CM_NVG_Master_C.ShowHintMaybe
// (BlueprintCallable, BlueprintEvent)

void UCM_NVG_Master_C::ShowHintMaybe()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "ShowHintMaybe");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CM_NVG_Master.CM_NVG_Master_C.OnPositionAlphaMet_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGBCharacter*                     Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_NVG_Master_C::OnPositionAlphaMet_Event_0(class AGBCharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "OnPositionAlphaMet_Event_0");

	Params::CM_NVG_Master_C_OnPositionAlphaMet_Event_0 Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_NVG_Master.CM_NVG_Master_C.BlueprintAddedToCamera
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// class AGBPlayerCameraManager*           GBPlayerCameraManager                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_NVG_Master_C::BlueprintAddedToCamera(class AGBPlayerCameraManager* GBPlayerCameraManager)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "BlueprintAddedToCamera");

	Params::CM_NVG_Master_C_BlueprintAddedToCamera Parms{};

	Parms.GBPlayerCameraManager = GBPlayerCameraManager;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_NVG_Master.CM_NVG_Master_C.BlueprintRemovedFromCamera
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// class AGBPlayerCameraManager*           GBPlayerCameraManager                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_NVG_Master_C::BlueprintRemovedFromCamera(class AGBPlayerCameraManager* GBPlayerCameraManager)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "BlueprintRemovedFromCamera");

	Params::CM_NVG_Master_C_BlueprintRemovedFromCamera Parms{};

	Parms.GBPlayerCameraManager = GBPlayerCameraManager;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_NVG_Master.CM_NVG_Master_C.SetPostProcessMID
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         InPPMID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_NVG_Master_C::SetPostProcessMID(class UMaterialInstanceDynamic* InPPMID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "SetPostProcessMID");

	Params::CM_NVG_Master_C_SetPostProcessMID Parms{};

	Parms.InPPMID = InPPMID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_NVG_Master.CM_NVG_Master_C.SetPostProcessMIDParameters
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   BlackAlpha                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   SceneAlpha                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_NVG_Master_C::SetPostProcessMIDParameters(float BlackAlpha, float SceneAlpha)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "SetPostProcessMIDParameters");

	Params::CM_NVG_Master_C_SetPostProcessMIDParameters Parms{};

	Parms.BlackAlpha = BlackAlpha;
	Parms.SceneAlpha = SceneAlpha;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_NVG_Master.CM_NVG_Master_C.BlueprintPreApplyCameraModifier
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// class AGBPlayerCameraManager*           GBPlayerCameraManager                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_NVG_Master_C::BlueprintPreApplyCameraModifier(class AGBPlayerCameraManager* GBPlayerCameraManager, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "BlueprintPreApplyCameraModifier");

	Params::CM_NVG_Master_C_BlueprintPreApplyCameraModifier Parms{};

	Parms.GBPlayerCameraManager = GBPlayerCameraManager;
	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CM_NVG_Master.CM_NVG_Master_C.AddNightVisionEnabledTag
// (BlueprintCallable, BlueprintEvent)

void UCM_NVG_Master_C::AddNightVisionEnabledTag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "AddNightVisionEnabledTag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CM_NVG_Master.CM_NVG_Master_C.RemoveNightVisionEnabledTag
// (BlueprintCallable, BlueprintEvent)

void UCM_NVG_Master_C::RemoveNightVisionEnabledTag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "RemoveNightVisionEnabledTag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CM_NVG_Master.CM_NVG_Master_C.OnModifierDisabledEvent
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)

void UCM_NVG_Master_C::OnModifierDisabledEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "OnModifierDisabledEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CM_NVG_Master.CM_NVG_Master_C.BlueprintModifyPostProcess
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  PostProcessBlendWeight_0                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPostProcessSettings*            PostProcessSettings                                    (Parm, OutParm)

void UCM_NVG_Master_C::BlueprintModifyPostProcess(float DeltaTime, float* PostProcessBlendWeight_0, struct FPostProcessSettings* PostProcessSettings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "BlueprintModifyPostProcess");

	Params::CM_NVG_Master_C_BlueprintModifyPostProcess Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);

	if (PostProcessBlendWeight_0 != nullptr)
		*PostProcessBlendWeight_0 = Parms.PostProcessBlendWeight_0;

	if (PostProcessSettings != nullptr)
		*PostProcessSettings = std::move(Parms.PostProcessSettings);
}


// Function CM_NVG_Master.CM_NVG_Master_C.BlueprintModifyCamera
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   ViewLocation                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FRotator&                  ViewRotation                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   FOV                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         NewViewLocation                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRotator*                        NewViewRotation                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float*                                  NewFOV                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCM_NVG_Master_C::BlueprintModifyCamera(float DeltaTime, const struct FVector& ViewLocation, const struct FRotator& ViewRotation, float FOV, struct FVector* NewViewLocation, struct FRotator* NewViewRotation, float* NewFOV)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CM_NVG_Master_C", "BlueprintModifyCamera");

	Params::CM_NVG_Master_C_BlueprintModifyCamera Parms{};

	Parms.DeltaTime = DeltaTime;
	Parms.ViewLocation = std::move(ViewLocation);
	Parms.ViewRotation = std::move(ViewRotation);
	Parms.FOV = FOV;

	UObject::ProcessEvent(Func, &Parms);

	if (NewViewLocation != nullptr)
		*NewViewLocation = std::move(Parms.NewViewLocation);

	if (NewViewRotation != nullptr)
		*NewViewRotation = std::move(Parms.NewViewRotation);

	if (NewFOV != nullptr)
		*NewFOV = Parms.NewFOV;
}

}

