#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_EmptyHands

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_ChangeEquipped_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_EmptyHands.GA_EmptyHands_C
// 0x0010 (0x04F0 - 0x04E0)
class UGA_EmptyHands_C final : public UGA_ChangeEquipped_Master_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_EmptyHands_C;                    // 0x04E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_EmptyHands(int32 EntryPoint);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_EmptyHands_C">();
	}
	static class UGA_EmptyHands_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_EmptyHands_C>();
	}
};
static_assert(alignof(UGA_EmptyHands_C) == 0x000010, "Wrong alignment on UGA_EmptyHands_C");
static_assert(sizeof(UGA_EmptyHands_C) == 0x0004F0, "Wrong size on UGA_EmptyHands_C");
static_assert(offsetof(UGA_EmptyHands_C, UberGraphFrame_GA_EmptyHands_C) == 0x0004E0, "Member 'UGA_EmptyHands_C::UberGraphFrame_GA_EmptyHands_C' has a wrong offset!");

}

