#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Grenade_ThrowSpeed_Master

#include "Basic.hpp"

#include "GA_Grenade_ThrowSpeed_Master_classes.hpp"
#include "GA_Grenade_ThrowSpeed_Master_parameters.hpp"


namespace SDK
{

// Function GA_Grenade_ThrowSpeed_Master.GA_Grenade_ThrowSpeed_Master_C.ExecuteUbergraph_GA_Grenade_ThrowSpeed_Master
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Grenade_ThrowSpeed_Master_C::ExecuteUbergraph_GA_Grenade_ThrowSpeed_Master(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Grenade_ThrowSpeed_Master_C", "ExecuteUbergraph_GA_Grenade_ThrowSpeed_Master");

	Params::GA_Grenade_ThrowSpeed_Master_C_ExecuteUbergraph_GA_Grenade_ThrowSpeed_Master Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Grenade_ThrowSpeed_Master.GA_Grenade_ThrowSpeed_Master_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Grenade_ThrowSpeed_Master_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Grenade_ThrowSpeed_Master_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Grenade_ThrowSpeed_Master.GA_Grenade_ThrowSpeed_Master_C.GetGrenadeArc
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_GrenadeArc_C**                OutGrenadeArc                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Grenade_ThrowSpeed_Master_C::GetGrenadeArc(class ABP_GrenadeArc_C** OutGrenadeArc)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Grenade_ThrowSpeed_Master_C", "GetGrenadeArc");

	Params::GA_Grenade_ThrowSpeed_Master_C_GetGrenadeArc Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutGrenadeArc != nullptr)
		*OutGrenadeArc = Parms.OutGrenadeArc;
}

}

