#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_NVG_FlipDown

#include "Basic.hpp"

#include "GA_NVG_FlipDown_classes.hpp"
#include "GA_NVG_FlipDown_parameters.hpp"


namespace SDK
{

// Function GA_NVG_FlipDown.GA_NVG_FlipDown_C.ExecuteUbergraph_GA_NVG_FlipDown
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_NVG_FlipDown_C::ExecuteUbergraph_GA_NVG_FlipDown(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NVG_FlipDown_C", "ExecuteUbergraph_GA_NVG_FlipDown");

	Params::GA_NVG_FlipDown_C_ExecuteUbergraph_GA_NVG_FlipDown Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_NVG_FlipDown.GA_NVG_FlipDown_C.WaitForNVGDownEvent
// (BlueprintCallable, BlueprintEvent)

void UGA_NVG_FlipDown_C::WaitForNVGDownEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NVG_FlipDown_C", "WaitForNVGDownEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_NVG_FlipDown.GA_NVG_FlipDown_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_NVG_FlipDown_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NVG_FlipDown_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_NVG_FlipDown.GA_NVG_FlipDown_C.EventReceived_C1B1165D12A24742BF35BF82E7775CF9
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_NVG_FlipDown_C::EventReceived_C1B1165D12A24742BF35BF82E7775CF9(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NVG_FlipDown_C", "EventReceived_C1B1165D12A24742BF35BF82E7775CF9");

	Params::GA_NVG_FlipDown_C_EventReceived_C1B1165D12A24742BF35BF82E7775CF9 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_NVG_FlipDown.GA_NVG_FlipDown_C.OnCompleted_8B0BC0D0EE67465AAC0105CEAE0688DC
// (BlueprintCallable, BlueprintEvent)

void UGA_NVG_FlipDown_C::OnCompleted_8B0BC0D0EE67465AAC0105CEAE0688DC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NVG_FlipDown_C", "OnCompleted_8B0BC0D0EE67465AAC0105CEAE0688DC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_NVG_FlipDown.GA_NVG_FlipDown_C.OnBlendOut_8B0BC0D0EE67465AAC0105CEAE0688DC
// (BlueprintCallable, BlueprintEvent)

void UGA_NVG_FlipDown_C::OnBlendOut_8B0BC0D0EE67465AAC0105CEAE0688DC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NVG_FlipDown_C", "OnBlendOut_8B0BC0D0EE67465AAC0105CEAE0688DC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_NVG_FlipDown.GA_NVG_FlipDown_C.OnInterrupted_8B0BC0D0EE67465AAC0105CEAE0688DC
// (BlueprintCallable, BlueprintEvent)

void UGA_NVG_FlipDown_C::OnInterrupted_8B0BC0D0EE67465AAC0105CEAE0688DC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NVG_FlipDown_C", "OnInterrupted_8B0BC0D0EE67465AAC0105CEAE0688DC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_NVG_FlipDown.GA_NVG_FlipDown_C.OnCancelled_8B0BC0D0EE67465AAC0105CEAE0688DC
// (BlueprintCallable, BlueprintEvent)

void UGA_NVG_FlipDown_C::OnCancelled_8B0BC0D0EE67465AAC0105CEAE0688DC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NVG_FlipDown_C", "OnCancelled_8B0BC0D0EE67465AAC0105CEAE0688DC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_NVG_FlipDown.GA_NVG_FlipDown_C.GetMontage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UAnimMontage**                    OutMontage                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_NVG_FlipDown_C::GetMontage(class UAnimMontage** OutMontage) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NVG_FlipDown_C", "GetMontage");

	Params::GA_NVG_FlipDown_C_GetMontage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutMontage != nullptr)
		*OutMontage = Parms.OutMontage;
}


// Function GA_NVG_FlipDown.GA_NVG_FlipDown_C.K2_CanActivateAbility
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const struct FGameplayAbilityActorInfo& ActorInfo                                              (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
// const struct FGameplayAbilitySpecHandle&Handle                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer*           RelevantTags                                           (Parm, OutParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UGA_NVG_FlipDown_C::K2_CanActivateAbility(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayAbilitySpecHandle& Handle, struct FGameplayTagContainer* RelevantTags) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NVG_FlipDown_C", "K2_CanActivateAbility");

	Params::GA_NVG_FlipDown_C_K2_CanActivateAbility Parms{};

	Parms.ActorInfo = std::move(ActorInfo);
	Parms.Handle = std::move(Handle);

	UObject::ProcessEvent(Func, &Parms);

	if (RelevantTags != nullptr)
		*RelevantTags = std::move(Parms.RelevantTags);

	return Parms.ReturnValue;
}

}

