#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MissionSummary_SplitContainer

#include "Basic.hpp"

#include "WBP_MissionSummary_SplitContainer_classes.hpp"
#include "WBP_MissionSummary_SplitContainer_parameters.hpp"


namespace SDK
{

// Function WBP_MissionSummary_SplitContainer.WBP_MissionSummary_SplitContainer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MissionSummary_SplitContainer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MissionSummary_SplitContainer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MissionSummary_SplitContainer.WBP_MissionSummary_SplitContainer_C.ExecuteUbergraph_WBP_MissionSummary_SplitContainer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MissionSummary_SplitContainer_C::ExecuteUbergraph_WBP_MissionSummary_SplitContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MissionSummary_SplitContainer_C", "ExecuteUbergraph_WBP_MissionSummary_SplitContainer");

	Params::WBP_MissionSummary_SplitContainer_C_ExecuteUbergraph_WBP_MissionSummary_SplitContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

