#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TravelFailureOverlay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TravelFailureOverlay.WBP_TravelFailureOverlay_C
// 0x0128 (0x0388 - 0x0260)
class UWBP_TravelFailureOverlay_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_Ok;                                         // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_ErrorTitle;                              // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Type;                                    // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TopBar;                                            // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_Messages;                              // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	ETravelFailure                                LastTravelFailureType;                             // 0x0298(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_299[0x7];                                      // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 LastTravelErrorMessage;                            // 0x02A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FText                                   MessageText;                                       // 0x02B0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   LoadMapFailure;                                    // 0x02C8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   NoLevel;                                           // 0x02E0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   NoLevelWithInfo;                                   // 0x02F8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   PackageMissing;                                    // 0x0310(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   PackageMissingDownloadFrom;                        // 0x0328(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   PendingNetGameCreateFailure;                       // 0x0340(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   ServerTravelFailure;                               // 0x0358(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   ClientTravelFailure;                               // 0x0370(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void BndEvt__Button_Password_Ok_K2Node_ComponentBoundEvent_735_OnButtonClickedEvent__DelegateSignature();
	void RemoveLoadingScreen();
	void Construct();
	void CheckPackageMissingURL();
	void CheckNoLevel();
	void ExecuteUbergraph_WBP_TravelFailureOverlay(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_TravelFailureOverlay_C">();
	}
	static class UWBP_TravelFailureOverlay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TravelFailureOverlay_C>();
	}
};
static_assert(alignof(UWBP_TravelFailureOverlay_C) == 0x000008, "Wrong alignment on UWBP_TravelFailureOverlay_C");
static_assert(sizeof(UWBP_TravelFailureOverlay_C) == 0x000388, "Wrong size on UWBP_TravelFailureOverlay_C");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, UberGraphFrame) == 0x000260, "Member 'UWBP_TravelFailureOverlay_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, Button_Ok) == 0x000268, "Member 'UWBP_TravelFailureOverlay_C::Button_Ok' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, Image_0) == 0x000270, "Member 'UWBP_TravelFailureOverlay_C::Image_0' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, TextBlock_ErrorTitle) == 0x000278, "Member 'UWBP_TravelFailureOverlay_C::TextBlock_ErrorTitle' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, TextBlock_Type) == 0x000280, "Member 'UWBP_TravelFailureOverlay_C::TextBlock_Type' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, TopBar) == 0x000288, "Member 'UWBP_TravelFailureOverlay_C::TopBar' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, VerticalBox_Messages) == 0x000290, "Member 'UWBP_TravelFailureOverlay_C::VerticalBox_Messages' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, LastTravelFailureType) == 0x000298, "Member 'UWBP_TravelFailureOverlay_C::LastTravelFailureType' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, LastTravelErrorMessage) == 0x0002A0, "Member 'UWBP_TravelFailureOverlay_C::LastTravelErrorMessage' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, MessageText) == 0x0002B0, "Member 'UWBP_TravelFailureOverlay_C::MessageText' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, LoadMapFailure) == 0x0002C8, "Member 'UWBP_TravelFailureOverlay_C::LoadMapFailure' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, NoLevel) == 0x0002E0, "Member 'UWBP_TravelFailureOverlay_C::NoLevel' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, NoLevelWithInfo) == 0x0002F8, "Member 'UWBP_TravelFailureOverlay_C::NoLevelWithInfo' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, PackageMissing) == 0x000310, "Member 'UWBP_TravelFailureOverlay_C::PackageMissing' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, PackageMissingDownloadFrom) == 0x000328, "Member 'UWBP_TravelFailureOverlay_C::PackageMissingDownloadFrom' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, PendingNetGameCreateFailure) == 0x000340, "Member 'UWBP_TravelFailureOverlay_C::PendingNetGameCreateFailure' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, ServerTravelFailure) == 0x000358, "Member 'UWBP_TravelFailureOverlay_C::ServerTravelFailure' has a wrong offset!");
static_assert(offsetof(UWBP_TravelFailureOverlay_C, ClientTravelFailure) == 0x000370, "Member 'UWBP_TravelFailureOverlay_C::ClientTravelFailure' has a wrong offset!");

}

