#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InGameMenu_MessageOverlay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_InGameMenu_MessageOverlay.WBP_InGameMenu_MessageOverlay_C
// 0x0040 (0x02A0 - 0x0260)
class UWBP_InGameMenu_MessageOverlay_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeOut;                                           // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FlashOn;                                           // 0x0270(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UTextBlock*                             MessageTextBlock;                                  // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_ServerMessages;                        // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnCancel;                                          // 0x0288(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	float                                         MessageDisplayTime;                                // 0x0298(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_InGameMenu_MessageOverlay(int32 EntryPoint);
	void OnDelayedFadeOutFinished();
	void OnFlashOnFinished();
	void Construct();
	void SetMessage(const class FText& Message);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_InGameMenu_MessageOverlay_C">();
	}
	static class UWBP_InGameMenu_MessageOverlay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InGameMenu_MessageOverlay_C>();
	}
};
static_assert(alignof(UWBP_InGameMenu_MessageOverlay_C) == 0x000008, "Wrong alignment on UWBP_InGameMenu_MessageOverlay_C");
static_assert(sizeof(UWBP_InGameMenu_MessageOverlay_C) == 0x0002A0, "Wrong size on UWBP_InGameMenu_MessageOverlay_C");
static_assert(offsetof(UWBP_InGameMenu_MessageOverlay_C, UberGraphFrame) == 0x000260, "Member 'UWBP_InGameMenu_MessageOverlay_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_InGameMenu_MessageOverlay_C, FadeOut) == 0x000268, "Member 'UWBP_InGameMenu_MessageOverlay_C::FadeOut' has a wrong offset!");
static_assert(offsetof(UWBP_InGameMenu_MessageOverlay_C, FlashOn) == 0x000270, "Member 'UWBP_InGameMenu_MessageOverlay_C::FlashOn' has a wrong offset!");
static_assert(offsetof(UWBP_InGameMenu_MessageOverlay_C, MessageTextBlock) == 0x000278, "Member 'UWBP_InGameMenu_MessageOverlay_C::MessageTextBlock' has a wrong offset!");
static_assert(offsetof(UWBP_InGameMenu_MessageOverlay_C, VerticalBox_ServerMessages) == 0x000280, "Member 'UWBP_InGameMenu_MessageOverlay_C::VerticalBox_ServerMessages' has a wrong offset!");
static_assert(offsetof(UWBP_InGameMenu_MessageOverlay_C, OnCancel) == 0x000288, "Member 'UWBP_InGameMenu_MessageOverlay_C::OnCancel' has a wrong offset!");
static_assert(offsetof(UWBP_InGameMenu_MessageOverlay_C, MessageDisplayTime) == 0x000298, "Member 'UWBP_InGameMenu_MessageOverlay_C::MessageDisplayTime' has a wrong offset!");

}

