#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OpsBoard_ChangeMissionSettings

#include "Basic.hpp"

#include "GroundBranch_structs.hpp"
#include "Struct_MissionSettingsEntry_WidgetData_structs.hpp"


namespace SDK::Params
{

// Function WBP_OpsBoard_ChangeMissionSettings.WBP_OpsBoard_ChangeMissionSettings_C.ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings
// 0x02B0 (0x02B0 - 0x0000)
struct WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const class FString& Option)>  K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBPlayerController*                    K2Node_DynamicCast_AsGBPlayer_Controller;          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBGameState*                           K2Node_DynamicCast_AsGBGame_State;                 // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_GetGameModeName_ReturnValue;              // 0x0054(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FGBMissionSetting>              CallFunc_GetMissionSettings_ReturnValue;           // 0x0060(0x0010)(ReferenceParm)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FGBMissionSetting                      CallFunc_Array_Get_Item;                           // 0x0080(0x0020)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_MissionSettingsEntry_WidgetData K2Node_MakeStruct_Struct_MissionSettingsEntry_WidgetData; // 0x00A8(0x0038)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x3];                                       // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_MissionSettings_TimeOfDay_C*       CallFunc_Create_ReturnValue;                       // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBPlayerControllerBase*                K2Node_DynamicCast_AsGBPlayer_Controller_Base;     // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_MissionSettings_Weather_C*         CallFunc_Create_ReturnValue_1;                     // 0x0110(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_Option;                         // 0x0118(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0128(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetAsOptionsString_OptionsString;         // 0x0148(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x0158(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetAsOptionsString_OptionsString_1;       // 0x0168(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0178(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBGameMode*                            K2Node_DynamicCast_AsGBGame_Mode;                  // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsStandalone_ReturnValue;                 // 0x0191(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_192[0x6];                                      // 0x0192(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_3;              // 0x0198(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1AC[0x4];                                      // 0x01AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_MissionSettingsEntry_WidgetData CallFunc_Array_Get_Item_1;                        // 0x01B0(0x0038)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x01EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1ED[0x3];                                      // 0x01ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue_1;       // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue_2;       // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue_3;       // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_1;                   // 0x0218(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBSky*                                 CallFunc_GetActorOfClass_ReturnValue;              // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable;                                // 0x0228(0x0018)()
	class FString                                 CallFunc_GetWeatherString_ReturnValue;             // 0x0240(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetTimeOfDayString_ReturnValue;           // 0x0250(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_261[0x7];                                      // 0x0261(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_1;                              // 0x0268(0x0018)()
	bool                                          Temp_bool_Variable;                                // 0x0280(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_281[0x7];                                      // 0x0281(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_MissionSettings_Entry_C*           CallFunc_Create_ReturnValue_2;                     // 0x0288(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Select_Default;                             // 0x0290(0x0018)()
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_2;                   // 0x02A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings) == 0x000008, "Wrong alignment on WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings");
static_assert(sizeof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings) == 0x0002B0, "Wrong size on WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, EntryPoint) == 0x000000, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetOwningPlayer_ReturnValue) == 0x000020, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_DynamicCast_AsGBPlayer_Controller) == 0x000028, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_DynamicCast_AsGBPlayer_Controller' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetGameState_ReturnValue) == 0x000038, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, Temp_int_Array_Index_Variable) == 0x000040, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_DynamicCast_AsGBGame_State) == 0x000048, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_DynamicCast_AsGBGame_State' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetGameModeName_ReturnValue) == 0x000054, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetGameModeName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetMissionSettings_ReturnValue) == 0x000060, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetMissionSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Conv_NameToString_ReturnValue) == 0x000070, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Array_Get_Item) == 0x000080, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Array_Length_ReturnValue) == 0x0000A0, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_MakeStruct_Struct_MissionSettingsEntry_WidgetData) == 0x0000A8, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_MakeStruct_Struct_MissionSettingsEntry_WidgetData' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Less_IntInt_ReturnValue) == 0x0000E0, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, Temp_int_Loop_Counter_Variable_1) == 0x0000E4, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Add_IntInt_ReturnValue_1) == 0x0000E8, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, Temp_int_Array_Index_Variable_1) == 0x0000EC, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Create_ReturnValue) == 0x0000F0, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetPlayerController_ReturnValue) == 0x0000F8, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_DynamicCast_AsGBPlayer_Controller_Base) == 0x000100, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_DynamicCast_AsGBPlayer_Controller_Base' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_DynamicCast_bSuccess_2) == 0x000108, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Create_ReturnValue_1) == 0x000110, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_CustomEvent_Option) == 0x000118, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_CustomEvent_Option' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Concat_StrStr_ReturnValue) == 0x000128, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000138, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetAsOptionsString_OptionsString) == 0x000148, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetAsOptionsString_OptionsString' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Concat_StrStr_ReturnValue_2) == 0x000158, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Concat_StrStr_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetAsOptionsString_OptionsString_1) == 0x000168, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetAsOptionsString_OptionsString_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_AddChild_ReturnValue) == 0x000178, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetGameMode_ReturnValue) == 0x000180, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_DynamicCast_AsGBGame_Mode) == 0x000188, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_DynamicCast_AsGBGame_Mode' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_DynamicCast_bSuccess_3) == 0x000190, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_IsStandalone_ReturnValue) == 0x000191, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_IsStandalone_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Concat_StrStr_ReturnValue_3) == 0x000198, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Concat_StrStr_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Array_Add_ReturnValue) == 0x0001A8, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Array_Get_Item_1) == 0x0001B0, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Array_Length_ReturnValue_1) == 0x0001E8, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Less_IntInt_ReturnValue_1) == 0x0001EC, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_PlayAnimationForward_ReturnValue) == 0x0001F0, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_PlayAnimationReverse_ReturnValue) == 0x0001F8, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_PlayAnimationReverse_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_PlayAnimationReverse_ReturnValue_1) == 0x000200, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_PlayAnimationReverse_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_PlayAnimationReverse_ReturnValue_2) == 0x000208, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_PlayAnimationReverse_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_PlayAnimationReverse_ReturnValue_3) == 0x000210, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_PlayAnimationReverse_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_AddChild_ReturnValue_1) == 0x000218, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_AddChild_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetActorOfClass_ReturnValue) == 0x000220, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetActorOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, Temp_text_Variable) == 0x000228, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetWeatherString_ReturnValue) == 0x000240, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetWeatherString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_GetTimeOfDayString_ReturnValue) == 0x000250, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_GetTimeOfDayString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_IsValid_ReturnValue) == 0x000260, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, Temp_text_Variable_1) == 0x000268, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, Temp_bool_Variable) == 0x000280, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_Create_ReturnValue_2) == 0x000288, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_Create_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, K2Node_Select_Default) == 0x000290, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings, CallFunc_AddChild_ReturnValue_2) == 0x0002A8, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_ExecuteUbergraph_WBP_OpsBoard_ChangeMissionSettings::CallFunc_AddChild_ReturnValue_2' has a wrong offset!");

// Function WBP_OpsBoard_ChangeMissionSettings.WBP_OpsBoard_ChangeMissionSettings_C.OnSettingChanged_Event_0
// 0x0010 (0x0010 - 0x0000)
struct WBP_OpsBoard_ChangeMissionSettings_C_OnSettingChanged_Event_0 final
{
public:
	class FString                                 Option;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OpsBoard_ChangeMissionSettings_C_OnSettingChanged_Event_0) == 0x000008, "Wrong alignment on WBP_OpsBoard_ChangeMissionSettings_C_OnSettingChanged_Event_0");
static_assert(sizeof(WBP_OpsBoard_ChangeMissionSettings_C_OnSettingChanged_Event_0) == 0x000010, "Wrong size on WBP_OpsBoard_ChangeMissionSettings_C_OnSettingChanged_Event_0");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_OnSettingChanged_Event_0, Option) == 0x000000, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_OnSettingChanged_Event_0::Option' has a wrong offset!");

// Function WBP_OpsBoard_ChangeMissionSettings.WBP_OpsBoard_ChangeMissionSettings_C.GetAsOptionsString
// 0x00E0 (0x00E0 - 0x0000)
struct WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString final
{
public:
	class FString                                 OptionsString;                                     // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 LocalOptionsString;                                // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TArray<class UWBP_MissionSettings_Entry_C*>   CallFunc_GetChildWidgetsOfClass_ChildWidgets;      // 0x0050(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UWBP_MissionSettings_Entry_C*           CallFunc_Array_Get_Item;                           // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_3;              // 0x0090(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_4;              // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_5;              // 0x00B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_6;              // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_7;              // 0x00D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString) == 0x000008, "Wrong alignment on WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString");
static_assert(sizeof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString) == 0x0000E0, "Wrong size on WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, OptionsString) == 0x000000, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::OptionsString' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, LocalOptionsString) == 0x000010, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::LocalOptionsString' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, Temp_int_Array_Index_Variable) == 0x000020, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, Temp_int_Loop_Counter_Variable) == 0x000024, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Concat_StrStr_ReturnValue) == 0x000030, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000040, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_GetChildWidgetsOfClass_ChildWidgets) == 0x000050, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_GetChildWidgetsOfClass_ChildWidgets' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Array_Get_Item) == 0x000060, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Array_Length_ReturnValue) == 0x000068, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Less_IntInt_ReturnValue) == 0x00006C, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Conv_IntToString_ReturnValue) == 0x000070, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Concat_StrStr_ReturnValue_2) == 0x000080, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Concat_StrStr_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Concat_StrStr_ReturnValue_3) == 0x000090, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Concat_StrStr_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Concat_StrStr_ReturnValue_4) == 0x0000A0, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Concat_StrStr_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Concat_StrStr_ReturnValue_5) == 0x0000B0, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Concat_StrStr_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Concat_StrStr_ReturnValue_6) == 0x0000C0, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Concat_StrStr_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString, CallFunc_Concat_StrStr_ReturnValue_7) == 0x0000D0, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_GetAsOptionsString::CallFunc_Concat_StrStr_ReturnValue_7' has a wrong offset!");

// Function WBP_OpsBoard_ChangeMissionSettings.WBP_OpsBoard_ChangeMissionSettings_C.Get_Button_Apply_bIsEnabled_0
// 0x0005 (0x0005 - 0x0000)
struct WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0 final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_StriStri_ReturnValue;            // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0) == 0x000001, "Wrong alignment on WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0");
static_assert(sizeof(WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0) == 0x000005, "Wrong size on WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0, ReturnValue) == 0x000000, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0, CallFunc_IsEmpty_ReturnValue) == 0x000001, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0::CallFunc_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0, CallFunc_NotEqual_StriStri_ReturnValue) == 0x000002, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0::CallFunc_NotEqual_StriStri_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0, CallFunc_Not_PreBool_ReturnValue) == 0x000003, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0, CallFunc_BooleanAND_ReturnValue) == 0x000004, "Member 'WBP_OpsBoard_ChangeMissionSettings_C_Get_Button_Apply_bIsEnabled_0::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");

}

