#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InvItemEditor

#include "Basic.hpp"

#include "WBP_InvItemEditor_classes.hpp"
#include "WBP_InvItemEditor_parameters.hpp"


namespace SDK
{

// Function WBP_InvItemEditor.WBP_InvItemEditor_C.ExecuteUbergraph_WBP_InvItemEditor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::ExecuteUbergraph_WBP_InvItemEditor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "ExecuteUbergraph_WBP_InvItemEditor");

	Params::WBP_InvItemEditor_C_ExecuteUbergraph_WBP_InvItemEditor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.SharedPrepAndApplyItemSkinIdMap
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::SharedPrepAndApplyItemSkinIdMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "SharedPrepAndApplyItemSkinIdMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.KitChangeMonitor
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::KitChangeMonitor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "KitChangeMonitor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.StartKitChangeMonitor
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::StartKitChangeMonitor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "StartKitChangeMonitor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.BndEvt__WBP_ItemEditor_CheckBox_ApplyToChildren_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_InvItemEditor_C::BndEvt__WBP_ItemEditor_CheckBox_ApplyToChildren_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "BndEvt__WBP_ItemEditor_CheckBox_ApplyToChildren_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::WBP_InvItemEditor_C_BndEvt__WBP_ItemEditor_CheckBox_ApplyToChildren_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.BndEvt__WBP_ItemEditor_ItemSkin_ComboBox_K2Node_ComponentBoundEvent_4_OnSkinIdSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const struct FPrimaryAssetId&           SkinId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::BndEvt__WBP_ItemEditor_ItemSkin_ComboBox_K2Node_ComponentBoundEvent_4_OnSkinIdSelected__DelegateSignature(const struct FPrimaryAssetId& SkinId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "BndEvt__WBP_ItemEditor_ItemSkin_ComboBox_K2Node_ComponentBoundEvent_4_OnSkinIdSelected__DelegateSignature");

	Params::WBP_InvItemEditor_C_BndEvt__WBP_ItemEditor_ItemSkin_ComboBox_K2Node_ComponentBoundEvent_4_OnSkinIdSelected__DelegateSignature Parms{};

	Parms.SkinId = std::move(SkinId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.InitItemSkinComboBox
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::InitItemSkinComboBox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "InitItemSkinComboBox");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnSettingChanged_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             OptionName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::OnSettingChanged_Event_0(class FName OptionName, int32 NewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnSettingChanged_Event_0");

	Params::WBP_InvItemEditor_C_OnSettingChanged_Event_0 Parms{};

	Parms.OptionName = OptionName;
	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.SetupRootItemSkin
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::SetupRootItemSkin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "SetupRootItemSkin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.PostConstruct
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::PostConstruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "PostConstruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.CreateItemBuildOptionWidget
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::CreateItemBuildOptionWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "CreateItemBuildOptionWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.SaveOverwriteCheck
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::SaveOverwriteCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "SaveOverwriteCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.BndEvt__WBP_ItemEditor_Button_SaveAs_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_InvItemEditor_C::BndEvt__WBP_ItemEditor_Button_SaveAs_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "BndEvt__WBP_ItemEditor_Button_SaveAs_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnOkClicked_Event_1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_DialogueBox_C*               Dialogue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::OnOkClicked_Event_1(class UWBP_DialogueBox_C* Dialogue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnOkClicked_Event_1");

	Params::WBP_InvItemEditor_C_OnOkClicked_Event_1 Parms{};

	Parms.Dialogue = Dialogue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.BndEvt__WBP_ItemEditor_Button_Clear_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_InvItemEditor_C::BndEvt__WBP_ItemEditor_Button_Clear_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "BndEvt__WBP_ItemEditor_Button_Clear_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_InvItemEditor_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnKitAssetsLoaded_Event
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class UObject*>&           LoadedAssets                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_InvItemEditor_C::OnKitAssetsLoaded_Event(const TArray<class UObject*>& LoadedAssets)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnKitAssetsLoaded_Event");

	Params::WBP_InvItemEditor_C_OnKitAssetsLoaded_Event Parms{};

	Parms.LoadedAssets = std::move(LoadedAssets);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.MoveArmsOutOfWay
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::MoveArmsOutOfWay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "MoveArmsOutOfWay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnCancelClicked_Event_0
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::OnCancelClicked_Event_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnCancelClicked_Event_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.SaveAsPrompt
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::SaveAsPrompt()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "SaveAsPrompt");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.Cancel
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::Cancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "Cancel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.MakeAllInteractive
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::MakeAllInteractive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "MakeAllInteractive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.AddItemCustomisationWidget
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::AddItemCustomisationWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "AddItemCustomisationWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnConfirmOkClicked_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_DialogueBox_C*               Dialogue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::OnConfirmOkClicked_Event_0(class UWBP_DialogueBox_C* Dialogue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnConfirmOkClicked_Event_0");

	Params::WBP_InvItemEditor_C_OnConfirmOkClicked_Event_0 Parms{};

	Parms.Dialogue = Dialogue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.SaveJsonObjToDisk
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::SaveJsonObjToDisk()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "SaveJsonObjToDisk");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnOkClicked_DoSave_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::OnOkClicked_DoSave_Event(const class FString& Filename)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnOkClicked_DoSave_Event");

	Params::WBP_InvItemEditor_C_OnOkClicked_DoSave_Event Parms{};

	Parms.Filename = std::move(Filename);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "Tick");

	Params::WBP_InvItemEditor_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.SetupAttachedItem
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 AttachedItemBounds_0                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   AttachedCameraVecOffset_0                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FRotator&                  AttachedCameraRotOffset_0                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_InvItemEditor_C::SetupAttachedItem(const struct FVector2D& AttachedItemBounds_0, const struct FVector& AttachedCameraVecOffset_0, const struct FRotator& AttachedCameraRotOffset_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "SetupAttachedItem");

	Params::WBP_InvItemEditor_C_SetupAttachedItem Parms{};

	Parms.AttachedItemBounds_0 = std::move(AttachedItemBounds_0);
	Parms.AttachedCameraVecOffset_0 = std::move(AttachedCameraVecOffset_0);
	Parms.AttachedCameraRotOffset_0 = std::move(AttachedCameraRotOffset_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.Close
// (BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "Close");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.BndEvt__Button_Cancel_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_InvItemEditor_C::BndEvt__Button_Cancel_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "BndEvt__Button_Cancel_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.BndEvt__Button_Ok_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_InvItemEditor_C::BndEvt__Button_Ok_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "BndEvt__Button_Ok_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.SetupFloatingItem
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   BoundsMultiplier                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ZOffset                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   XOffset                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   PitchOffset                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   YawOffset                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bOffsetItemBy90                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_InvItemEditor_C::SetupFloatingItem(float BoundsMultiplier, float ZOffset, float XOffset, float PitchOffset, float YawOffset, bool bOffsetItemBy90)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "SetupFloatingItem");

	Params::WBP_InvItemEditor_C_SetupFloatingItem Parms{};

	Parms.BoundsMultiplier = BoundsMultiplier;
	Parms.ZOffset = ZOffset;
	Parms.XOffset = XOffset;
	Parms.PitchOffset = PitchOffset;
	Parms.YawOffset = YawOffset;
	Parms.bOffsetItemBy90 = bOffsetItemBy90;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_InvItemEditor_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.Completed_16950A03920346EFA03F6C83777EE459
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class UObject*>&           Loaded                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_InvItemEditor_C::Completed_16950A03920346EFA03F6C83777EE459(const TArray<class UObject*>& Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "Completed_16950A03920346EFA03F6C83777EE459");

	Params::WBP_InvItemEditor_C_Completed_16950A03920346EFA03F6C83777EE459 Parms{};

	Parms.Loaded = std::move(Loaded);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.Completed_57E34F25027142E684BFEC1008E73A32
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class UObject*>&           Loaded                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_InvItemEditor_C::Completed_57E34F25027142E684BFEC1008E73A32(const TArray<class UObject*>& Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "Completed_57E34F25027142E684BFEC1008E73A32");

	Params::WBP_InvItemEditor_C_Completed_57E34F25027142E684BFEC1008E73A32 Parms{};

	Parms.Loaded = std::move(Loaded);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.Completed_D494691E0C9446C1AE0D3C795FE48508
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class UObject*>&           Loaded                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_InvItemEditor_C::Completed_D494691E0C9446C1AE0D3C795FE48508(const TArray<class UObject*>& Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "Completed_D494691E0C9446C1AE0D3C795FE48508");

	Params::WBP_InvItemEditor_C_Completed_D494691E0C9446C1AE0D3C795FE48508 Parms{};

	Parms.Loaded = std::move(Loaded);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.Completed_F7D295B345644C0DBEECEE40AC987DFC
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class UObject*>&           Loaded                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_InvItemEditor_C::Completed_F7D295B345644C0DBEECEE40AC987DFC(const TArray<class UObject*>& Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "Completed_F7D295B345644C0DBEECEE40AC987DFC");

	Params::WBP_InvItemEditor_C_Completed_F7D295B345644C0DBEECEE40AC987DFC Parms{};

	Parms.Loaded = std::move(Loaded);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.MoveCamera
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 MouseDelta                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::MoveCamera(const struct FVector2D& MouseDelta)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "MoveCamera");

	Params::WBP_InvItemEditor_C_MoveCamera Parms{};

	Parms.MouseDelta = std::move(MouseDelta);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.RotateItemOrChar
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 MouseDelta                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::RotateItemOrChar(const struct FVector2D& MouseDelta)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "RotateItemOrChar");

	Params::WBP_InvItemEditor_C_RotateItemOrChar Parms{};

	Parms.MouseDelta = std::move(MouseDelta);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.Zoom Camera
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   WheelDelta                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::Zoom_Camera(float WheelDelta)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "Zoom Camera");

	Params::WBP_InvItemEditor_C_Zoom_Camera Parms{};

	Parms.WheelDelta = WheelDelta;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnMouseMove
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_InvItemEditor_C::OnMouseMove(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnMouseMove");

	Params::WBP_InvItemEditor_C_OnMouseMove Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnMouseWheel
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_InvItemEditor_C::OnMouseWheel(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnMouseWheel");

	Params::WBP_InvItemEditor_C_OnMouseWheel Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.MakeInteractive
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InActor                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::MakeInteractive(class AActor* InActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "MakeInteractive");

	Params::WBP_InvItemEditor_C_MakeInteractive Parms{};

	Parms.InActor = InActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnDragDetected
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             PointerEvent                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UDragDropOperation**              Operation                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::OnDragDetected(const struct FGeometry& MyGeometry, const struct FPointerEvent& PointerEvent, class UDragDropOperation** Operation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnDragDetected");

	Params::WBP_InvItemEditor_C_OnDragDetected Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.PointerEvent = std::move(PointerEvent);

	UObject::ProcessEvent(Func, &Parms);

	if (Operation != nullptr)
		*Operation = Parms.Operation;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.UpdateItemUnderCursor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_InvItemEditor_C::UpdateItemUnderCursor(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "UpdateItemUnderCursor");

	Params::WBP_InvItemEditor_C_UpdateItemUnderCursor Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_InvItemEditor_C::OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnMouseButtonDown");

	Params::WBP_InvItemEditor_C_OnMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.GetHoveredInvItemTooltip
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_InvItemEditor_C::GetHoveredInvItemTooltip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "GetHoveredInvItemTooltip");

	Params::WBP_InvItemEditor_C_GetHoveredInvItemTooltip Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.IsValidSetup
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bOutIsValid                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText*                            OutInvalidMessage                                      (Parm, OutParm)

void UWBP_InvItemEditor_C::IsValidSetup(bool* bOutIsValid, class FText* OutInvalidMessage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "IsValidSetup");

	Params::WBP_InvItemEditor_C_IsValidSetup Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bOutIsValid != nullptr)
		*bOutIsValid = Parms.bOutIsValid;

	if (OutInvalidMessage != nullptr)
		*OutInvalidMessage = std::move(Parms.OutInvalidMessage);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_InvItemEditor_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnKeyDown");

	Params::WBP_InvItemEditor_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.OnKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_InvItemEditor_C::OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "OnKeyUp");

	Params::WBP_InvItemEditor_C_OnKeyUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.NukeEditorRelatedActors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::NukeEditorRelatedActors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "NukeEditorRelatedActors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.GetButtonSaveEnabled
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWBP_InvItemEditor_C::GetButtonSaveEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "GetButtonSaveEnabled");

	Params::WBP_InvItemEditor_C_GetButtonSaveEnabled Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.CreateNewItemJsonObj
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bSuccess                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_InvItemEditor_C::CreateNewItemJsonObj(bool* bSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "CreateNewItemJsonObj");

	Params::WBP_InvItemEditor_C_CreateNewItemJsonObj Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bSuccess != nullptr)
		*bSuccess = Parms.bSuccess;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.PrepItemToItemSkinIdMap
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FPrimaryAssetId>*         OutItemSkinsToLoad                                     (Parm, OutParm)

void UWBP_InvItemEditor_C::PrepItemToItemSkinIdMap(TArray<struct FPrimaryAssetId>* OutItemSkinsToLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "PrepItemToItemSkinIdMap");

	Params::WBP_InvItemEditor_C_PrepItemToItemSkinIdMap Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutItemSkinsToLoad != nullptr)
		*OutItemSkinsToLoad = std::move(Parms.OutItemSkinsToLoad);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.ApplyItemToItemSkinMap
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::ApplyItemToItemSkinMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "ApplyItemToItemSkinMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.DetermineExcludedActors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::DetermineExcludedActors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "DetermineExcludedActors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.SetBuildName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    NewBuildName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::SetBuildName(const class FString& NewBuildName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "SetBuildName");

	Params::WBP_InvItemEditor_C_SetBuildName Parms{};

	Parms.NewBuildName = std::move(NewBuildName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.UpdateBuildNameUsingLua
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_InvItemEditor_C::UpdateBuildNameUsingLua()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "UpdateBuildNameUsingLua");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.GetFirstInvItemMatchingMostTags
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGBCharacter*                     InGBCharacter                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AGBInvItem**                      OutFirstInvItem                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::GetFirstInvItemMatchingMostTags(class AGBCharacter* InGBCharacter, class AGBInvItem** OutFirstInvItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "GetFirstInvItemMatchingMostTags");

	Params::WBP_InvItemEditor_C_GetFirstInvItemMatchingMostTags Parms{};

	Parms.InGBCharacter = InGBCharacter;

	UObject::ProcessEvent(Func, &Parms);

	if (OutFirstInvItem != nullptr)
		*OutFirstInvItem = Parms.OutFirstInvItem;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.GetDragDropVisualsInfo
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGBInvItem*                       InDraggedItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText*                            OutDisplayText                                         (Parm, OutParm)
// TSoftObjectPtr<class UTexture2D>*       OutIcon                                                (Parm, OutParm, UObjectWrapper, HasGetValueTypeHash)

void UWBP_InvItemEditor_C::GetDragDropVisualsInfo(class AGBInvItem* InDraggedItem, class FText* OutDisplayText, TSoftObjectPtr<class UTexture2D>* OutIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "GetDragDropVisualsInfo");

	Params::WBP_InvItemEditor_C_GetDragDropVisualsInfo Parms{};

	Parms.InDraggedItem = InDraggedItem;

	UObject::ProcessEvent(Func, &Parms);

	if (OutDisplayText != nullptr)
		*OutDisplayText = std::move(Parms.OutDisplayText);

	if (OutIcon != nullptr)
		*OutIcon = Parms.OutIcon;
}


// Function WBP_InvItemEditor.WBP_InvItemEditor_C.GetApplyToChildrenText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_InvItemEditor_C::GetApplyToChildrenText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InvItemEditor_C", "GetApplyToChildrenText");

	Params::WBP_InvItemEditor_C_GetApplyToChildrenText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

