#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ME_Dialogue_PickScreenshots

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_ME_Dialogue_PickScreenshots.WBP_ME_Dialogue_PickScreenshots_C.BuildListViewEntries
// 0x0068 (0x0068 - 0x0000)
struct WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_ME_ScreenshotFileObj_C*             CallFunc_SpawnObject_ReturnValue;                  // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<TSoftObjectPtr<class UTexture2D>>      CallFunc_GetMapScreenshots_OutScreenShotPtrs;      // 0x0020(0x0010)(ReferenceParm)
	bool                                          CallFunc_GetMapScreenshots_ReturnValue;            // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              CallFunc_Array_Get_Item;                           // 0x0038(0x0028)(HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries) == 0x000008, "Wrong alignment on WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries");
static_assert(sizeof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries) == 0x000068, "Wrong size on WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries, CallFunc_SpawnObject_ReturnValue) == 0x000010, "Member 'WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries, CallFunc_Array_Add_ReturnValue) == 0x000018, "Member 'WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries, CallFunc_GetMapScreenshots_OutScreenShotPtrs) == 0x000020, "Member 'WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries::CallFunc_GetMapScreenshots_OutScreenShotPtrs' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries, CallFunc_GetMapScreenshots_ReturnValue) == 0x000030, "Member 'WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries::CallFunc_GetMapScreenshots_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries, CallFunc_Array_Length_ReturnValue) == 0x000034, "Member 'WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries, CallFunc_Array_Get_Item) == 0x000038, "Member 'WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries, CallFunc_Less_IntInt_ReturnValue) == 0x000060, "Member 'WBP_ME_Dialogue_PickScreenshots_C_BuildListViewEntries::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_ME_Dialogue_PickScreenshots.WBP_ME_Dialogue_PickScreenshots_C.Create Screenshot Name List
// 0x0080 (0x0080 - 0x0000)
struct WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List final
{
public:
	class FString                                 ScreenshotNameList_0;                              // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 NewString;                                         // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item;                           // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_LeftChop_ReturnValue;                     // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List) == 0x000008, "Wrong alignment on WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List");
static_assert(sizeof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List) == 0x000080, "Wrong size on WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, ScreenshotNameList_0) == 0x000000, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::ScreenshotNameList_0' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, NewString) == 0x000010, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::NewString' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, Temp_int_Array_Index_Variable) == 0x000020, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, Temp_int_Loop_Counter_Variable) == 0x000024, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, CallFunc_Array_Get_Item) == 0x000030, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, CallFunc_Array_Length_ReturnValue) == 0x000040, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, CallFunc_Concat_StrStr_ReturnValue) == 0x000048, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, CallFunc_Less_IntInt_ReturnValue) == 0x000058, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000060, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List, CallFunc_LeftChop_ReturnValue) == 0x000070, "Member 'WBP_ME_Dialogue_PickScreenshots_C_Create_Screenshot_Name_List::CallFunc_LeftChop_ReturnValue' has a wrong offset!");

// Function WBP_ME_Dialogue_PickScreenshots.WBP_ME_Dialogue_PickScreenshots_C.OnOkClicked_Event
// 0x0008 (0x0008 - 0x0000)
struct WBP_ME_Dialogue_PickScreenshots_C_OnOkClicked_Event final
{
public:
	class UWBP_DialogueBox_C*                     Dialogue;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ME_Dialogue_PickScreenshots_C_OnOkClicked_Event) == 0x000008, "Wrong alignment on WBP_ME_Dialogue_PickScreenshots_C_OnOkClicked_Event");
static_assert(sizeof(WBP_ME_Dialogue_PickScreenshots_C_OnOkClicked_Event) == 0x000008, "Wrong size on WBP_ME_Dialogue_PickScreenshots_C_OnOkClicked_Event");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_OnOkClicked_Event, Dialogue) == 0x000000, "Member 'WBP_ME_Dialogue_PickScreenshots_C_OnOkClicked_Event::Dialogue' has a wrong offset!");

// Function WBP_ME_Dialogue_PickScreenshots.WBP_ME_Dialogue_PickScreenshots_C.ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots
// 0x0048 (0x0048 - 0x0000)
struct WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_DialogueBox_C*                     CallFunc_GetParentWidgetOfClass_ReturnValue;       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DialogueBox_C*                     K2Node_CustomEvent_dialogue;                       // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Create_Screenshot_Name_List_ScreenshotNameList; // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0028(0x0010)(ZeroConstructor, NoDestructor)
	class UWBP_DialogueBox_C*                     CallFunc_GetParentWidgetOfClass_ReturnValue_1;     // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DialogueBox_C*                     CallFunc_GetParentWidgetOfClass_ReturnValue_2;     // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots) == 0x000008, "Wrong alignment on WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots");
static_assert(sizeof(WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots) == 0x000048, "Wrong size on WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots, EntryPoint) == 0x000000, "Member 'WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots, CallFunc_GetParentWidgetOfClass_ReturnValue) == 0x000008, "Member 'WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots::CallFunc_GetParentWidgetOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots, K2Node_CustomEvent_dialogue) == 0x000010, "Member 'WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots::K2Node_CustomEvent_dialogue' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots, CallFunc_Create_Screenshot_Name_List_ScreenshotNameList) == 0x000018, "Member 'WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots::CallFunc_Create_Screenshot_Name_List_ScreenshotNameList' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots, K2Node_CreateDelegate_OutputDelegate) == 0x000028, "Member 'WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots, CallFunc_GetParentWidgetOfClass_ReturnValue_1) == 0x000038, "Member 'WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots::CallFunc_GetParentWidgetOfClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots, CallFunc_GetParentWidgetOfClass_ReturnValue_2) == 0x000040, "Member 'WBP_ME_Dialogue_PickScreenshots_C_ExecuteUbergraph_WBP_ME_Dialogue_PickScreenshots::CallFunc_GetParentWidgetOfClass_ReturnValue_2' has a wrong offset!");

}

