#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Hint_Manager

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_Hint_Manager.WBP_Hint_Manager_C.ExecuteUbergraph_WBP_Hint_Manager
// 0x0080 (0x0080 - 0x0000)
struct WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class AGBHUD* GBHUD)>          K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	class AGBPlayerController*                    K2Node_DynamicCast_AsGBPlayer_Controller;          // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBHUD*                                 CallFunc_GetGBHUD_ReturnValue;                     // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_CustomEvent_HintWidgetClass;                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_Create_ReturnValue;                       // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_Hint_Wrapper_C*                    CallFunc_GetHintWrapperByHintClass_OutHintWrapper; // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_Hint_Wrapper_C*                    CallFunc_Create_ReturnValue_1;                     // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerticalBoxSlot*                       CallFunc_AddChildToVerticalBox_ReturnValue;        // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6A[0x6];                                       // 0x006A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBHUD*                                 K2Node_CustomEvent_GBHUD;                          // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager) == 0x000008, "Wrong alignment on WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager");
static_assert(sizeof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager) == 0x000080, "Wrong size on WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, EntryPoint) == 0x000000, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, Temp_bool_Variable) == 0x000004, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, CallFunc_GetOwningPlayer_ReturnValue) == 0x000008, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, K2Node_DynamicCast_AsGBPlayer_Controller) == 0x000020, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::K2Node_DynamicCast_AsGBPlayer_Controller' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, CallFunc_GetGBHUD_ReturnValue) == 0x000030, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::CallFunc_GetGBHUD_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, K2Node_CustomEvent_HintWidgetClass) == 0x000038, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::K2Node_CustomEvent_HintWidgetClass' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, CallFunc_Create_ReturnValue) == 0x000040, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, CallFunc_GetHintWrapperByHintClass_OutHintWrapper) == 0x000048, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::CallFunc_GetHintWrapperByHintClass_OutHintWrapper' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, CallFunc_IsValid_ReturnValue) == 0x000050, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, CallFunc_Create_ReturnValue_1) == 0x000058, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, CallFunc_AddChildToVerticalBox_ReturnValue) == 0x000060, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::CallFunc_AddChildToVerticalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, Temp_byte_Variable) == 0x000068, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, Temp_byte_Variable_1) == 0x000069, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, K2Node_CustomEvent_GBHUD) == 0x000070, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::K2Node_CustomEvent_GBHUD' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager, K2Node_Select_Default) == 0x000078, "Member 'WBP_Hint_Manager_C_ExecuteUbergraph_WBP_Hint_Manager::K2Node_Select_Default' has a wrong offset!");

// Function WBP_Hint_Manager.WBP_Hint_Manager_C.OnShowHUDChanged_Event_0
// 0x0008 (0x0008 - 0x0000)
struct WBP_Hint_Manager_C_OnShowHUDChanged_Event_0 final
{
public:
	class AGBHUD*                                 GBHUD;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Hint_Manager_C_OnShowHUDChanged_Event_0) == 0x000008, "Wrong alignment on WBP_Hint_Manager_C_OnShowHUDChanged_Event_0");
static_assert(sizeof(WBP_Hint_Manager_C_OnShowHUDChanged_Event_0) == 0x000008, "Wrong size on WBP_Hint_Manager_C_OnShowHUDChanged_Event_0");
static_assert(offsetof(WBP_Hint_Manager_C_OnShowHUDChanged_Event_0, GBHUD) == 0x000000, "Member 'WBP_Hint_Manager_C_OnShowHUDChanged_Event_0::GBHUD' has a wrong offset!");

// Function WBP_Hint_Manager.WBP_Hint_Manager_C.AddHint
// 0x0008 (0x0008 - 0x0000)
struct WBP_Hint_Manager_C_AddHint final
{
public:
	class UClass*                                 HintWidgetClass;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Hint_Manager_C_AddHint) == 0x000008, "Wrong alignment on WBP_Hint_Manager_C_AddHint");
static_assert(sizeof(WBP_Hint_Manager_C_AddHint) == 0x000008, "Wrong size on WBP_Hint_Manager_C_AddHint");
static_assert(offsetof(WBP_Hint_Manager_C_AddHint, HintWidgetClass) == 0x000000, "Member 'WBP_Hint_Manager_C_AddHint::HintWidgetClass' has a wrong offset!");

// Function WBP_Hint_Manager.WBP_Hint_Manager_C.GetHintWrapperByHintClass
// 0x0068 (0x0068 - 0x0000)
struct WBP_Hint_Manager_C_GetHintWrapperByHintClass final
{
public:
	class UClass*                                 HintClass;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_Hint_Wrapper_C*                    OutHintWrapper;                                    // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_Hint_Wrapper_C*                    LocalHintWrapper;                                  // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWBP_Hint_Wrapper_C*>            CallFunc_GetChildWidgetsOfClass_ChildWidgets;      // 0x0030(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_Hint_Wrapper_C*                    CallFunc_Array_Get_Item;                           // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_Hint_Manager_C_GetHintWrapperByHintClass) == 0x000008, "Wrong alignment on WBP_Hint_Manager_C_GetHintWrapperByHintClass");
static_assert(sizeof(WBP_Hint_Manager_C_GetHintWrapperByHintClass) == 0x000068, "Wrong size on WBP_Hint_Manager_C_GetHintWrapperByHintClass");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, HintClass) == 0x000000, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::HintClass' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, OutHintWrapper) == 0x000008, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::OutHintWrapper' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, LocalHintWrapper) == 0x000010, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::LocalHintWrapper' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, Temp_int_Array_Index_Variable) == 0x000018, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, Temp_bool_True_if_break_was_hit_Variable) == 0x00001C, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_Not_PreBool_ReturnValue) == 0x00001D, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, Temp_int_Loop_Counter_Variable) == 0x000020, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_Subtract_IntInt_ReturnValue) == 0x000024, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000028, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_BooleanAND_ReturnValue) == 0x000029, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_GetChildWidgetsOfClass_ChildWidgets) == 0x000030, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_GetChildWidgetsOfClass_ChildWidgets' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_Array_Length_ReturnValue) == 0x000040, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_Array_Get_Item) == 0x000048, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x000050, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_Max_ReturnValue) == 0x000054, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_GetObjectClass_ReturnValue) == 0x000058, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Hint_Manager_C_GetHintWrapperByHintClass, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x000060, "Member 'WBP_Hint_Manager_C_GetHintWrapperByHintClass::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");

}

