#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CE_PatchSelection_Button

#include "Basic.hpp"

#include "WBP_CE_PatchSelection_Button_classes.hpp"
#include "WBP_CE_PatchSelection_Button_parameters.hpp"


namespace SDK
{

// Function WBP_CE_PatchSelection_Button.WBP_CE_PatchSelection_Button_C.ExecuteUbergraph_WBP_CE_PatchSelection_Button
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CE_PatchSelection_Button_C::ExecuteUbergraph_WBP_CE_PatchSelection_Button(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_PatchSelection_Button_C", "ExecuteUbergraph_WBP_CE_PatchSelection_Button");

	Params::WBP_CE_PatchSelection_Button_C_ExecuteUbergraph_WBP_CE_PatchSelection_Button Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CE_PatchSelection_Button.WBP_CE_PatchSelection_Button_C.ClearPresets
// (BlueprintCallable, BlueprintEvent)

void UWBP_CE_PatchSelection_Button_C::ClearPresets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_PatchSelection_Button_C", "ClearPresets");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CE_PatchSelection_Button.WBP_CE_PatchSelection_Button_C.OnApply_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVaRestJsonObject*                PathJsonObj                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CE_PatchSelection_Button_C::OnApply_Event_0(class UVaRestJsonObject* PathJsonObj)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_PatchSelection_Button_C", "OnApply_Event_0");

	Params::WBP_CE_PatchSelection_Button_C_OnApply_Event_0 Parms{};

	Parms.PathJsonObj = PathJsonObj;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CE_PatchSelection_Button.WBP_CE_PatchSelection_Button_C.BndEvt__WBP_Button_Item_Button_ItemList_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_CE_PatchSelection_Button_C::BndEvt__WBP_Button_Item_Button_ItemList_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_PatchSelection_Button_C", "BndEvt__WBP_Button_Item_Button_ItemList_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CE_PatchSelection_Button.WBP_CE_PatchSelection_Button_C.BndEvt__WBP_Button_Item_Button_ItemList_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_CE_PatchSelection_Button_C::BndEvt__WBP_Button_Item_Button_ItemList_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_PatchSelection_Button_C", "BndEvt__WBP_Button_Item_Button_ItemList_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CE_PatchSelection_Button.WBP_CE_PatchSelection_Button_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CE_PatchSelection_Button_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_PatchSelection_Button_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CE_PatchSelection_Button.WBP_CE_PatchSelection_Button_C.BndEvt__Button_ItemList_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_CE_PatchSelection_Button_C::BndEvt__Button_ItemList_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_PatchSelection_Button_C", "BndEvt__Button_ItemList_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CE_PatchSelection_Button.WBP_CE_PatchSelection_Button_C.HasBeenChanged
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWBP_CE_PatchSelection_Button_C::HasBeenChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_PatchSelection_Button_C", "HasBeenChanged");

	Params::WBP_CE_PatchSelection_Button_C_HasBeenChanged Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_CE_PatchSelection_Button.WBP_CE_PatchSelection_Button_C.GetPatchesJsonData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UVaRestJsonObject*>*       OutPatchesJsonData                                     (Parm, OutParm)

void UWBP_CE_PatchSelection_Button_C::GetPatchesJsonData(TArray<class UVaRestJsonObject*>* OutPatchesJsonData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_PatchSelection_Button_C", "GetPatchesJsonData");

	Params::WBP_CE_PatchSelection_Button_C_GetPatchesJsonData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutPatchesJsonData != nullptr)
		*OutPatchesJsonData = std::move(Parms.OutPatchesJsonData);
}


// Function WBP_CE_PatchSelection_Button.WBP_CE_PatchSelection_Button_C.Update
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVaRestJsonObject*                InKitJsonObj                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInFromPreset                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_CE_PatchSelection_Button_C::Update(class UVaRestJsonObject* InKitJsonObj, bool bInFromPreset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_PatchSelection_Button_C", "Update");

	Params::WBP_CE_PatchSelection_Button_C_Update Parms{};

	Parms.InKitJsonObj = InKitJsonObj;
	Parms.bInFromPreset = bInFromPreset;

	UObject::ProcessEvent(Func, &Parms);
}

}

