#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Audio

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Audio.Audio
// 0x0004 (0x0004 - 0x0000)
struct FAudio final
{
public:
	float                                         BasePerceptionScale_33_D3CA79F248E2ED671283C9BFABF1591D; // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FAudio) == 0x000004, "Wrong alignment on FAudio");
static_assert(sizeof(FAudio) == 0x000004, "Wrong size on FAudio");
static_assert(offsetof(FAudio, BasePerceptionScale_33_D3CA79F248E2ED671283C9BFABF1591D) == 0x000000, "Member 'FAudio::BasePerceptionScale_33_D3CA79F248E2ED671283C9BFABF1591D' has a wrong offset!");

}

