#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BloodImpact_Default

#include "Basic.hpp"

#include "BP_BloodImpact_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BloodImpact_Default.BP_BloodImpact_Default_C
// 0x0000 (0x02B8 - 0x02B8)
class ABP_BloodImpact_Default_C final : public ABP_BloodImpact_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BloodImpact_Default_C">();
	}
	static class ABP_BloodImpact_Default_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BloodImpact_Default_C>();
	}
};
static_assert(alignof(ABP_BloodImpact_Default_C) == 0x000008, "Wrong alignment on ABP_BloodImpact_Default_C");
static_assert(sizeof(ABP_BloodImpact_Default_C) == 0x0002B8, "Wrong size on ABP_BloodImpact_Default_C");

}

