#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Chemlight_Projectile

#include "Basic.hpp"

#include "BP_Chemlight_Projectile_classes.hpp"
#include "BP_Chemlight_Projectile_parameters.hpp"


namespace SDK
{

// Function BP_Chemlight_Projectile.BP_Chemlight_Projectile_C.ExecuteUbergraph_BP_Chemlight_Projectile
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Chemlight_Projectile_C::ExecuteUbergraph_BP_Chemlight_Projectile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Chemlight_Projectile_C", "ExecuteUbergraph_BP_Chemlight_Projectile");

	Params::BP_Chemlight_Projectile_C_ExecuteUbergraph_BP_Chemlight_Projectile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Chemlight_Projectile.BP_Chemlight_Projectile_C.OnReplaceClientsideProxyEvent
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AGBInvItem*                       ClientsideProxyAssociatedItem                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bSyncedLocations                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Chemlight_Projectile_C::OnReplaceClientsideProxyEvent(class AGBInvItem* ClientsideProxyAssociatedItem, bool bSyncedLocations)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Chemlight_Projectile_C", "OnReplaceClientsideProxyEvent");

	Params::BP_Chemlight_Projectile_C_OnReplaceClientsideProxyEvent Parms{};

	Parms.ClientsideProxyAssociatedItem = ClientsideProxyAssociatedItem;
	Parms.bSyncedLocations = bSyncedLocations;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Chemlight_Projectile.BP_Chemlight_Projectile_C.AlignToFloor
// (BlueprintCallable, BlueprintEvent)

void ABP_Chemlight_Projectile_C::AlignToFloor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Chemlight_Projectile_C", "AlignToFloor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Chemlight_Projectile.BP_Chemlight_Projectile_C.BndEvt__BP_Chemlight_Projectile_ItemProjectileMovement_K2Node_ComponentBoundEvent_0_OnProjectileStopDelegate__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult&                ImpactResult                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Chemlight_Projectile_C::BndEvt__BP_Chemlight_Projectile_ItemProjectileMovement_K2Node_ComponentBoundEvent_0_OnProjectileStopDelegate__DelegateSignature(const struct FHitResult& ImpactResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Chemlight_Projectile_C", "BndEvt__BP_Chemlight_Projectile_ItemProjectileMovement_K2Node_ComponentBoundEvent_0_OnProjectileStopDelegate__DelegateSignature");

	Params::BP_Chemlight_Projectile_C_BndEvt__BP_Chemlight_Projectile_ItemProjectileMovement_K2Node_ComponentBoundEvent_0_OnProjectileStopDelegate__DelegateSignature Parms{};

	Parms.ImpactResult = std::move(ImpactResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Chemlight_Projectile.BP_Chemlight_Projectile_C.OnComponentHit_Event_0
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Chemlight_Projectile_C::OnComponentHit_Event_0(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Chemlight_Projectile_C", "OnComponentHit_Event_0");

	Params::BP_Chemlight_Projectile_C_OnComponentHit_Event_0 Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Chemlight_Projectile.BP_Chemlight_Projectile_C.OnRep_bAlignToFloor
// (BlueprintCallable, BlueprintEvent)

void ABP_Chemlight_Projectile_C::OnRep_bAlignToFloor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Chemlight_Projectile_C", "OnRep_bAlignToFloor");

	UObject::ProcessEvent(Func, nullptr);
}

}

