#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TacLight_Master

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function BP_TacLight_Master.BP_TacLight_Master_C.ExecuteUbergraph_BP_TacLight_Master
// 0x0110 (0x0110 - 0x0000)
struct BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool bLightActive, bool bLightVisibility)> K2Node_CreateDelegate_OutputDelegate;  // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_1;          // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBCharacter*                           K2Node_Event_Character_1;                          // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_RadialMenu_Entry_C*                CallFunc_Create_ReturnValue;                       // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            K2Node_Event_UsageMenu;                            // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Index;                          // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_RadialMenu_C*                      K2Node_DynamicCast_AsWBP_Radial_Menu;              // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetLightActive_OutActive;                 // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x004B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetDisplayName_ReturnValue;               // 0x0050(0x0018)()
	class UNiagaraComponent*                      CallFunc_GetComponentByClass_ReturnValue;          // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         CallFunc_GetAsset_ReturnValue;                     // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7B[0x5];                                       // 0x007B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBCharacter*                           K2Node_Event_Character;                            // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_bLightActive;                   // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_bLightVisibility;               // 0x008A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8B[0x1];                                       // 0x008B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_BoolToFloat_ReturnValue;             // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMeshComponent*                         CallFunc_GetComponentByClass_ReturnValue_1;        // 0x0090(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetIcon_ReturnValue;                      // 0x0098(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	class UMaterialInterface*                     CallFunc_GetMaterial_ReturnValue;                  // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               K2Node_DynamicCast_AsMaterial_Instance_Dynamic;    // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue;              // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Temp_struct_Variable;                              // 0x00E0(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 Index)>                  K2Node_CreateDelegate_OutputDelegate_1;            // 0x00E8(0x0010)(ZeroConstructor, NoDestructor)
	class UNiagaraSystem*                         CallFunc_GetEffect_ReturnValue;                    // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Temp_struct_Variable_1;                            // 0x0100(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           K2Node_Select_Default;                             // 0x0108(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master) == 0x000008, "Wrong alignment on BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master");
static_assert(sizeof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master) == 0x000110, "Wrong size on BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, EntryPoint) == 0x000000, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, Temp_bool_Variable) == 0x000004, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_IsDedicatedServer_ReturnValue) == 0x000019, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_Not_PreBool_ReturnValue) == 0x00001A, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_IsDedicatedServer_ReturnValue_1) == 0x00001B, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_IsDedicatedServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_Event_Character_1) == 0x000020, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_Event_Character_1' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_Create_ReturnValue) == 0x000028, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_Event_UsageMenu) == 0x000030, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_Event_UsageMenu' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_CustomEvent_Index) == 0x000038, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_CustomEvent_Index' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_DynamicCast_AsWBP_Radial_Menu) == 0x000040, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_DynamicCast_AsWBP_Radial_Menu' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_GetLightActive_OutActive) == 0x000049, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_GetLightActive_OutActive' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_IsValid_ReturnValue_1) == 0x00004A, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_IsValid_ReturnValue_2) == 0x00004B, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_GetDisplayName_ReturnValue) == 0x000050, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_GetComponentByClass_ReturnValue) == 0x000068, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_GetAsset_ReturnValue) == 0x000070, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_GetAsset_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_IsServer_ReturnValue) == 0x000078, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_IsValid_ReturnValue_3) == 0x000079, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_Not_PreBool_ReturnValue_1) == 0x00007A, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_Event_Character) == 0x000080, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_Event_Character' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_IsValid_ReturnValue_4) == 0x000088, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_CustomEvent_bLightActive) == 0x000089, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_CustomEvent_bLightActive' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_CustomEvent_bLightVisibility) == 0x00008A, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_CustomEvent_bLightVisibility' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_Conv_BoolToFloat_ReturnValue) == 0x00008C, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_Conv_BoolToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_GetComponentByClass_ReturnValue_1) == 0x000090, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_GetComponentByClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_GetIcon_ReturnValue) == 0x000098, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_GetIcon_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_GetMaterial_ReturnValue) == 0x0000C0, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_GetMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_DynamicCast_AsMaterial_Instance_Dynamic) == 0x0000C8, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_DynamicCast_AsMaterial_Instance_Dynamic' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_DynamicCast_bSuccess_1) == 0x0000D0, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_GetGBInstigator_ReturnValue) == 0x0000D8, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_GetGBInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, Temp_struct_Variable) == 0x0000E0, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000E8, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, CallFunc_GetEffect_ReturnValue) == 0x0000F8, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::CallFunc_GetEffect_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, Temp_struct_Variable_1) == 0x000100, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master, K2Node_Select_Default) == 0x000108, "Member 'BP_TacLight_Master_C_ExecuteUbergraph_BP_TacLight_Master::K2Node_Select_Default' has a wrong offset!");

// Function BP_TacLight_Master.BP_TacLight_Master_C.OnLightActiveEvent_Event_0
// 0x0002 (0x0002 - 0x0000)
struct BP_TacLight_Master_C_OnLightActiveEvent_Event_0 final
{
public:
	bool                                          bLightActive;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bLightVisibility;                                  // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_TacLight_Master_C_OnLightActiveEvent_Event_0) == 0x000001, "Wrong alignment on BP_TacLight_Master_C_OnLightActiveEvent_Event_0");
static_assert(sizeof(BP_TacLight_Master_C_OnLightActiveEvent_Event_0) == 0x000002, "Wrong size on BP_TacLight_Master_C_OnLightActiveEvent_Event_0");
static_assert(offsetof(BP_TacLight_Master_C_OnLightActiveEvent_Event_0, bLightActive) == 0x000000, "Member 'BP_TacLight_Master_C_OnLightActiveEvent_Event_0::bLightActive' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_OnLightActiveEvent_Event_0, bLightVisibility) == 0x000001, "Member 'BP_TacLight_Master_C_OnLightActiveEvent_Event_0::bLightVisibility' has a wrong offset!");

// Function BP_TacLight_Master.BP_TacLight_Master_C.OnAddedToInventoryEvent
// 0x0008 (0x0008 - 0x0000)
struct BP_TacLight_Master_C_OnAddedToInventoryEvent final
{
public:
	class AGBCharacter*                           Character;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TacLight_Master_C_OnAddedToInventoryEvent) == 0x000008, "Wrong alignment on BP_TacLight_Master_C_OnAddedToInventoryEvent");
static_assert(sizeof(BP_TacLight_Master_C_OnAddedToInventoryEvent) == 0x000008, "Wrong size on BP_TacLight_Master_C_OnAddedToInventoryEvent");
static_assert(offsetof(BP_TacLight_Master_C_OnAddedToInventoryEvent, Character) == 0x000000, "Member 'BP_TacLight_Master_C_OnAddedToInventoryEvent::Character' has a wrong offset!");

// Function BP_TacLight_Master.BP_TacLight_Master_C.OnSelected_Event_0
// 0x0004 (0x0004 - 0x0000)
struct BP_TacLight_Master_C_OnSelected_Event_0 final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TacLight_Master_C_OnSelected_Event_0) == 0x000004, "Wrong alignment on BP_TacLight_Master_C_OnSelected_Event_0");
static_assert(sizeof(BP_TacLight_Master_C_OnSelected_Event_0) == 0x000004, "Wrong size on BP_TacLight_Master_C_OnSelected_Event_0");
static_assert(offsetof(BP_TacLight_Master_C_OnSelected_Event_0, Index_0) == 0x000000, "Member 'BP_TacLight_Master_C_OnSelected_Event_0::Index_0' has a wrong offset!");

// Function BP_TacLight_Master.BP_TacLight_Master_C.AddAttachedUseMenuEntries
// 0x0008 (0x0008 - 0x0000)
struct BP_TacLight_Master_C_AddAttachedUseMenuEntries final
{
public:
	class UUserWidget*                            UsageMenu;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TacLight_Master_C_AddAttachedUseMenuEntries) == 0x000008, "Wrong alignment on BP_TacLight_Master_C_AddAttachedUseMenuEntries");
static_assert(sizeof(BP_TacLight_Master_C_AddAttachedUseMenuEntries) == 0x000008, "Wrong size on BP_TacLight_Master_C_AddAttachedUseMenuEntries");
static_assert(offsetof(BP_TacLight_Master_C_AddAttachedUseMenuEntries, UsageMenu) == 0x000000, "Member 'BP_TacLight_Master_C_AddAttachedUseMenuEntries::UsageMenu' has a wrong offset!");

// Function BP_TacLight_Master.BP_TacLight_Master_C.OnRemovedFromInventoryEvent
// 0x0008 (0x0008 - 0x0000)
struct BP_TacLight_Master_C_OnRemovedFromInventoryEvent final
{
public:
	class AGBCharacter*                           Character;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TacLight_Master_C_OnRemovedFromInventoryEvent) == 0x000008, "Wrong alignment on BP_TacLight_Master_C_OnRemovedFromInventoryEvent");
static_assert(sizeof(BP_TacLight_Master_C_OnRemovedFromInventoryEvent) == 0x000008, "Wrong size on BP_TacLight_Master_C_OnRemovedFromInventoryEvent");
static_assert(offsetof(BP_TacLight_Master_C_OnRemovedFromInventoryEvent, Character) == 0x000000, "Member 'BP_TacLight_Master_C_OnRemovedFromInventoryEvent::Character' has a wrong offset!");

// Function BP_TacLight_Master.BP_TacLight_Master_C.UserConstructionScript
// 0x0008 (0x0008 - 0x0000)
struct BP_TacLight_Master_C_UserConstructionScript final
{
public:
	class UBP_GBItemFlashLightComponent_C*        CallFunc_GetComponentByClass_ReturnValue;          // 0x0000(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TacLight_Master_C_UserConstructionScript) == 0x000008, "Wrong alignment on BP_TacLight_Master_C_UserConstructionScript");
static_assert(sizeof(BP_TacLight_Master_C_UserConstructionScript) == 0x000008, "Wrong size on BP_TacLight_Master_C_UserConstructionScript");
static_assert(offsetof(BP_TacLight_Master_C_UserConstructionScript, CallFunc_GetComponentByClass_ReturnValue) == 0x000000, "Member 'BP_TacLight_Master_C_UserConstructionScript::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");

// Function BP_TacLight_Master.BP_TacLight_Master_C.AllowUsageWhileAttached
// 0x0002 (0x0002 - 0x0000)
struct BP_TacLight_Master_C_AllowUsageWhileAttached final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsEquipped_ReturnValue;                   // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_TacLight_Master_C_AllowUsageWhileAttached) == 0x000001, "Wrong alignment on BP_TacLight_Master_C_AllowUsageWhileAttached");
static_assert(sizeof(BP_TacLight_Master_C_AllowUsageWhileAttached) == 0x000002, "Wrong size on BP_TacLight_Master_C_AllowUsageWhileAttached");
static_assert(offsetof(BP_TacLight_Master_C_AllowUsageWhileAttached, ReturnValue) == 0x000000, "Member 'BP_TacLight_Master_C_AllowUsageWhileAttached::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TacLight_Master_C_AllowUsageWhileAttached, CallFunc_IsEquipped_ReturnValue) == 0x000001, "Member 'BP_TacLight_Master_C_AllowUsageWhileAttached::CallFunc_IsEquipped_ReturnValue' has a wrong offset!");

}

