#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Chemlight_Throw

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Grenade_Throw_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Chemlight_Throw.GA_Chemlight_Throw_C
// 0x0008 (0x0470 - 0x0468)
class UGA_Chemlight_Throw_C final : public UGA_Grenade_Throw_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Chemlight_Throw_C;               // 0x0468(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Chemlight_Throw(int32 EntryPoint);
	void ActivateShared();
	void EventReceived_26F8B4649CAC44DABDA5DBB270258AE4(const struct FGameplayEventData& Payload);

	void GetLaunchVelocity(struct FVector* OutVelocity) const;
	void GetDesiredSpawnLocation(struct FVector* OutDesiredSpawnLocation) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Chemlight_Throw_C">();
	}
	static class UGA_Chemlight_Throw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Chemlight_Throw_C>();
	}
};
static_assert(alignof(UGA_Chemlight_Throw_C) == 0x000008, "Wrong alignment on UGA_Chemlight_Throw_C");
static_assert(sizeof(UGA_Chemlight_Throw_C) == 0x000470, "Wrong size on UGA_Chemlight_Throw_C");
static_assert(offsetof(UGA_Chemlight_Throw_C, UberGraphFrame_GA_Chemlight_Throw_C) == 0x000468, "Member 'UGA_Chemlight_Throw_C::UberGraphFrame_GA_Chemlight_Throw_C' has a wrong offset!");

}

