#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Tab_Master

#include "Basic.hpp"

#include "WBP_Tab_Master_classes.hpp"
#include "WBP_Tab_Master_parameters.hpp"


namespace SDK
{

// Function WBP_Tab_Master.WBP_Tab_Master_C.ExecuteUbergraph_WBP_Tab_Master
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Tab_Master_C::ExecuteUbergraph_WBP_Tab_Master(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tab_Master_C", "ExecuteUbergraph_WBP_Tab_Master");

	Params::WBP_Tab_Master_C_ExecuteUbergraph_WBP_Tab_Master Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Tab_Master.WBP_Tab_Master_C.SetInitiallySelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   SelectionDelay                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Tab_Master_C::SetInitiallySelected(float SelectionDelay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tab_Master_C", "SetInitiallySelected");

	Params::WBP_Tab_Master_C_SetInitiallySelected Parms{};

	Parms.SelectionDelay = SelectionDelay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Tab_Master.WBP_Tab_Master_C.InternalSetSelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelected                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Tab_Master_C::InternalSetSelected(bool IsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tab_Master_C", "InternalSetSelected");

	Params::WBP_Tab_Master_C_InternalSetSelected Parms{};

	Parms.IsSelected = IsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Tab_Master.WBP_Tab_Master_C.InternalStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsChecked_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Tab_Master_C::InternalStateChanged(bool IsChecked_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tab_Master_C", "InternalStateChanged");

	Params::WBP_Tab_Master_C_InternalStateChanged Parms{};

	Parms.IsChecked_0 = IsChecked_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Tab_Master.WBP_Tab_Master_C.InternalOnSelected
// (BlueprintCallable, BlueprintEvent)

void UWBP_Tab_Master_C::InternalOnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tab_Master_C", "InternalOnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Tab_Master.WBP_Tab_Master_C.SetSelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelected                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Tab_Master_C::SetSelected(bool IsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tab_Master_C", "SetSelected");

	Params::WBP_Tab_Master_C_SetSelected Parms{};

	Parms.IsSelected = IsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Tab_Master.WBP_Tab_Master_C.GetTabTextFontColour
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UWBP_Tab_Master_C::GetTabTextFontColour()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tab_Master_C", "GetTabTextFontColour");

	Params::WBP_Tab_Master_C_GetTabTextFontColour Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Tab_Master.WBP_Tab_Master_C.GetTabTextFontShadowColour
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_Tab_Master_C::GetTabTextFontShadowColour()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tab_Master_C", "GetTabTextFontShadowColour");

	Params::WBP_Tab_Master_C_GetTabTextFontShadowColour Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Tab_Master.WBP_Tab_Master_C.IsValidClass
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          ChildWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsValid                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Tab_Master_C::IsValidClass(class UWidget* ChildWidget, bool* IsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tab_Master_C", "IsValidClass");

	Params::WBP_Tab_Master_C_IsValidClass Parms{};

	Parms.ChildWidget = ChildWidget;

	UObject::ProcessEvent(Func, &Parms);

	if (IsValid != nullptr)
		*IsValid = Parms.IsValid;
}

}

