#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CE_ListFilters_InvItemSkins

#include "Basic.hpp"

#include "WBP_CE_ListFilters_InvItemSkins_classes.hpp"
#include "WBP_CE_ListFilters_InvItemSkins_parameters.hpp"


namespace SDK
{

// Function WBP_CE_ListFilters_InvItemSkins.WBP_CE_ListFilters_InvItemSkins_C.ExecuteUbergraph_WBP_CE_ListFilters_InvItemSkins
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CE_ListFilters_InvItemSkins_C::ExecuteUbergraph_WBP_CE_ListFilters_InvItemSkins(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_ListFilters_InvItemSkins_C", "ExecuteUbergraph_WBP_CE_ListFilters_InvItemSkins");

	Params::WBP_CE_ListFilters_InvItemSkins_C_ExecuteUbergraph_WBP_CE_ListFilters_InvItemSkins Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CE_ListFilters_InvItemSkins.WBP_CE_ListFilters_InvItemSkins_C.BndEvt__WBP_CE_ListFilters_InvItems_WBP_CE_ListFilter_Category_ShowModsOnly_K2Node_ComponentBoundEvent_15_OnCheckStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_CE_ListFilters_InvItemSkins_C::BndEvt__WBP_CE_ListFilters_InvItems_WBP_CE_ListFilter_Category_ShowModsOnly_K2Node_ComponentBoundEvent_15_OnCheckStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_ListFilters_InvItemSkins_C", "BndEvt__WBP_CE_ListFilters_InvItems_WBP_CE_ListFilter_Category_ShowModsOnly_K2Node_ComponentBoundEvent_15_OnCheckStateChanged__DelegateSignature");

	Params::WBP_CE_ListFilters_InvItemSkins_C_BndEvt__WBP_CE_ListFilters_InvItems_WBP_CE_ListFilter_Category_ShowModsOnly_K2Node_ComponentBoundEvent_15_OnCheckStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CE_ListFilters_InvItemSkins.WBP_CE_ListFilters_InvItemSkins_C.BndEvt__WBP_CE_ListFilters_InvItems_WBP_CE_ListFilter_Category_HideMods_K2Node_ComponentBoundEvent_14_OnCheckStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_CE_ListFilters_InvItemSkins_C::BndEvt__WBP_CE_ListFilters_InvItems_WBP_CE_ListFilter_Category_HideMods_K2Node_ComponentBoundEvent_14_OnCheckStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_ListFilters_InvItemSkins_C", "BndEvt__WBP_CE_ListFilters_InvItems_WBP_CE_ListFilter_Category_HideMods_K2Node_ComponentBoundEvent_14_OnCheckStateChanged__DelegateSignature");

	Params::WBP_CE_ListFilters_InvItemSkins_C_BndEvt__WBP_CE_ListFilters_InvItems_WBP_CE_ListFilter_Category_HideMods_K2Node_ComponentBoundEvent_14_OnCheckStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CE_ListFilters_InvItemSkins.WBP_CE_ListFilters_InvItemSkins_C.GetFiltersToolTipText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText*                            OutFilterToolTipText                                   (Parm, OutParm)

void UWBP_CE_ListFilters_InvItemSkins_C::GetFiltersToolTipText(class FText* OutFilterToolTipText) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CE_ListFilters_InvItemSkins_C", "GetFiltersToolTipText");

	Params::WBP_CE_ListFilters_InvItemSkins_C_GetFiltersToolTipText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutFilterToolTipText != nullptr)
		*OutFilterToolTipText = std::move(Parms.OutFilterToolTipText);
}

}

